### ISSUE TITLE
Enhacement: Change default sleeping Owl behaviour to show almost all columns and form items like Grocery Crud

### ISSUE THREAD

**Issue by acacha** [sleeping-owl/admin#102]
Congratulations awesome tool!

Like lot of developers I started learning and using Laravel coming from Code Igniter. For a very long time I've been searching a Laravel tool to substitute Grocery Crud (http://www.grocerycrud.com/) and at the moment sleeping-owl is the best tool I've found.

But one of the things I love more about Crocery Crud is "zero" configuration. By zero configuration I mean you only have to provide a table name and a default CRUD system is builded with all fields shown on table view and creating and editing forms. Then if you needed you can config/restrict your CRUD. Also is awesome how form field types are autoconfigured from MySQL types.

I'm not aware how difficult is to implement this behaviour or maybe all I say is nonsense but I think it could be amazing having a full crud system with only the following model configuration:

Admin::model('\App\User');

with a lot of default behaviour applied.

Kind regards,

Sergi Tur

**Comment by sleeping-owl** [comment]
There is artisan command for that purpose (http://sleeping-owl.github.io/v3/en/Commands/Model_Configuration_Generation.html):
```bash
php artisan admin:model "App\MyModel"
```

It will generate model configuration with all columns from database and form with fields based on database column types. I think this even better because you can change it as you want.

**Comment by acacha** [comment]
Awesome! Thank you for your aswer!

**Comment by acacha** [comment]
Ok I've tested it. 

For default User model in Laravel Scaffolding (after change parent class toSleepingOwlModel) if I execute:

$ php artisan admin:model "\App\User"


The result file is:

```php
<?php

Admin::model(\App\User::class)->title('')->with()->filters(function ()
{

})->columns(function ()
{

})->form(function ()
{
	FormItem::text('name', 'Name');
	FormItem::text('email', 'Email');
	FormItem::text('password', 'Password');
	FormItem::text('remember_token', 'Remember Token');
});
```
Two thinks. First I've to change:

```php
Admin::model(\App\User::class)->title('')->with()->filters(function ()
```

to

```php
Admin::model('\App\User')->title('')->with()->filters(function ()
```

to avoid Error:

ErrorException in Models.php line 48:
Model with classname [\App\User] not registered as admin module.

Second: I propose to fill default columns if not columns are specified (maybe showing no hidden  and|or fillable fields)

**Comment by sleeping-owl** [comment]
First: fixed
Second: I'll think about it and add it when I'd have a bit more free time

**Comment by jaikishanprajpaat** [comment]
my question ?insert data from a form in multiple table

**Comment by sleeping-owl** [comment]
This package creates crud behavior. So one page = one entry in one table. You can use tabbed display to show more than one entry on page.
