### ISSUE TITLE
Question: How best to support multilingual models

### ISSUE THREAD

**Issue by johnshepherd** [sleeping-owl/admin#103]
I'd like to use a package such as [dimsav/laravel-translatable](https://github.com/dimsav/laravel-translatable) to support multilingual models and edit these through the Admin (v3). What would be the recommended way of doing this? I'm not looking for a completed solution, just an opinion on what the best way would be to tackle it? 

Thanks!

**Comment by sleeping-owl** [comment]
I've used that package. And there is my solution:
- Create middleware to set locale for admin (https://gist.github.com/sleeping-owl/7ccb20cb3fc1f2494911)
- Add it as global middleware in `Kernel.php`
- Create controller with action that changes session `admin.locale` value
- Override header template and add language selection block (`resources/views/vendor/admin/default/_partials/header.blade.php`)

Administrator can select locale and show/edit only this locale.

**Comment by johnshepherd** [comment]
Wonderful thank you, didn't think of that approach.
