### ISSUE TITLE
Problems with timestamps in V3

### ISSUE THREAD

**Issue by noxify** [sleeping-owl/admin#104]
Hi,

currently I have the problem that the timestamps `created_at` and `updated_at ` are not working as expected.

In the `config/app.php` the timezone is "UTC".

After creating a new user, the values are the following:

* created_at = 2015-05-23 02:09:30
* updated_at = 2015-05-23 02:09:30

The timestamps after creation are correct.

Now I click on save and the timestamp are the following:

* created_at = 2015-05-23 02:14:06 (which is the current timestamp)
* updated_at = 2015-05-23 00:14:06 (looks like the UTC timestamp)

Now what I can see is:
* updated_at will be updated, but with the wrong timezone => config file
* created_at will be updated with the current timestamp => Bug or Feature?! ;) 

I'm using in my Admin Model the `createAndEdit()` function but it's also not working with `create()` and `edit()` function.

ENV:
* OSX
* MAMP
* latest stable laravel
* admin package v3
* admin lte theme

Thanks :)

**Comment by eugenem** [comment]
Check that your db table isn't configured to update created_at automatically. I don't think that Admin even knows about timestamps.

**Comment by sleeping-owl** [comment]
This package uses default Eloquent behavior:
```php
$model = YourModel::find($id);
$model->fill(…);
$model->save();
```

`created_at` and `updated_at` fields are setted by Eloquent logic and my package doesn't change it.
