### ISSUE TITLE
Custom Actions Buttons for Form View in V3

### ISSUE THREAD

**Issue by noxify** [sleeping-owl/admin#105]
Hi,

is it possible to implement the actions() functionality which exists in the list view also for the form view?

Currently, my workaround is to use columns inside a tabbed form.

Thanks!

**Comment by sleeping-owl** [comment]
You can create your own form items and implement any functions you want. You can create pull request and I will merge it to the main package. Now I can't implement new features due to the time lack, but will add this issue as a milestone.

**Comment by noxify** [comment]
I will create the pull request next week :)

Thanks :)
