### ISSUE TITLE
Many to many - column name ambiguous error

### ISSUE THREAD

**Issue by sameerpanjwani** [sleeping-owl/admin#106]
I have a model "Property", "Tag" and a "PropertyTag" pivot.

In the "Property" Model:

public function tags()
    {
        return $this->belongsToMany('App\Tag', 'property_tag');
    }

In the "Tag" model:

 public function properties()
    {
        return $this->belongsToMany('App\Property', 'property_tag');
    }

 public static function getList()
    {
        return static::lists('tag_name', 'tag_id');
    }

When I try to list the tags in the Property model like follows: 

FormItem::multiSelect('tags','Tags')->list('\App\Tag')->required()->value('tags.tag_id');

It fails because "tag_id" is ambiguous since "tag_id" is mentioned both on the "Tag" table as the priimary key and the "property_tag" table. I think your script assumes that the "Tag" table should have an "id" column as it's primary key but it doesn't in my case and I can't change it. 

I also change the getList() function to:

 return static::select('tag_name','tag_id as _id')->lists('tag_name', '_id');

That also returns the data but still the same error because I can't seem to change the way the *->value()* field is mentioned.

**Comment by sleeping-owl** [comment]
It seems like an error with your relation. Eloquent default belongsToMany relation can work only with `id` primary keys.
