### ISSUE TITLE
v3 ordering buttons

### ISSUE THREAD

**Issue by eugenem** [sleeping-owl/admin#108]
I've complained about v2 regarding this, now it looks the same at v3.
There is my model:
````
<?php

namespace App\Models;


class Category extends \Eloquent
{
    public $timestamps = false;

    protected $guarded = ['id'];

    use \SleepingOwl\Admin\Traits\OrderableModel;

    public function getOrderField()
    {
        return 'ordr';
    }

    public function subcategories()
    {
        return $this->hasMany('App\Models\Subcategory');
    }

    public static function getList()
    {
        $vals = [];
        foreach( self::all() as $item )
            $vals[$item->id] = $item->name;

        return $vals;
    }

}

````
There is definition for admin:
````
Admin::model('App\Models\Category')
    ->title('Categories')
    ->display(function ()
    {
        $display = AdminDisplay::datatables();
        $display->columns([
            Column::string('name')->label('Name'),
            Column::order(),
        ]);
        return $display;
    })->createAndEdit(function ()
    {
        $form = AdminForm::form();
        $form->items([
            FormItem::text('name', 'Name'),
        ]);
        return $form;
    });
````
This is what's in DB: https://www.dropbox.com/s/j0160s6i50sox2y/Screenshot%202015-05-24%2023.08.48.png?dl=0
And this is what's at admin: https://www.dropbox.com/s/hn5ea461ax15ihk/Screenshot%202015-05-24%2023.09.15.png?dl=0
or if I sort by order column: https://www.dropbox.com/s/j8f9t60vphqeabe/Screenshot%202015-05-24%2023.09.42.png?dl=0

**Comment by eugenem** [comment]
i see, it can be solved by adding first column for order number:
````
Admin::model('App\Models\Category')
    ->title('Categories')
    ->display(function ()
    {
        $display = AdminDisplay::datatables();
        $display->columns([
            Column::string('ordr')->label('Order'),
            Column::string('name')->label('Name'),
            Column::order(),
        ]);
        return $display;
    })->createAndEdit(function ()
    {
        $form = AdminForm::form();
        $form->items([
            FormItem::text('name', 'Name'),
        ]);
        return $form;
    });
````

Note that it works properly only when numbering starts from 0.

**Comment by sleeping-owl** [comment]
You can use table display type (https://github.com/sleeping-owl/admin-3-demo/blob/master/app/admin/Country.php) and lock sort by your order column.

Datatables plugin reorder all data after page load, you can set column to order by in datatables format (https://github.com/sleeping-owl/admin-3-demo/blob/master/app/admin/News2.php).

You can add order column to your datatables or use table display type.
