### ISSUE TITLE
Дополнительные атрибуты элементов форм

### ISSUE THREAD

**Issue by Denwebart** [sleeping-owl/admin#11]
Здравствуйте. Хотелось бы иметь возможность добавлять html-атрибуты к полям либо к контейнеру form-group.
Например, так:
FormItem::text('meta_title', 'Мета-тег Title')->htmlOptions(['class' => 'customclass']);
или
FormItem::text('meta_title', 'Мета-тег Title', ['class' => 'customclass']);

**Comment by sleeping-owl** [comment]
Добавил. Доступно в версии 1.1.6. Можно использовать так (в документацию добавлю позже):
```php
FormItem::text('firstName', 'First Name')->attributes(['class' => 'my-class', 'my-attribute' => 1]);
```

**Comment by Denwebart** [comment]
Спасибо большое!
