### ISSUE TITLE
Image Resizing in v3 ?

### ISSUE THREAD

**Issue by Elyahou** [sleeping-owl/admin#115]
Is this feature exist on admin v3 ?

**Comment by sleeping-owl** [comment]
No, this feature was moved out of the package. You can use [intervention/image](http://image.intervention.io) package to perform image resizing features. This is not an area of responsibility of admin package and I don't want to limit developers by my choice.

**Comment by avilaj** [comment]
Sorry for bring up this closed issue.

How can I do this? I want to reutilize the FormItem::images object
But to have the images in multiple sizes. Since it's for a gallery.

How would you proceed on this?
