### ISSUE TITLE
Multiple Roles (e.g. for Translators)

### ISSUE THREAD

**Issue by netconception** [sleeping-owl/admin#117]
Hello!

First I say sorry for my bad english, I'm from Germany!

I need to have more then 1 role, who has access to the administrator panel, e.g. for an external translation company. 

My customer wants to have seperated rights for administrator and translators. the translators only can see the menu points for translation topics.

Is this possible to setup?

Greetings!

**Comment by noxify** [comment]
Hi,

What you can do currently without a lot of effort.

Create a new MenuItem Class, which extends the existing one:
https://github.com/sleeping-owl/admin/blob/development/src/SleepingOwl/Admin/Menu/MenuItem.php

In your own class you have to create a new method() "adminOnly" or something like this.
In this method you have to check some Conditions (like an isAdmin flag in the administrators table)

Then you have to modify the render() function which includes your new method.
After this, modify the view which checks your new argument.

I think this is the fastest way to hide the menu entries from the menu.

Hope this helps.

**Comment by netconception** [comment]
Thanks for your answer. I will check this and give feedback.

**Comment by noxify** [comment]
But the described workaround will only hide the menu items. If the user knows the url path he/she can change the url in the browser :)

**Comment by netconception** [comment]
Then I need a filter or so ?

**Comment by noxify** [comment]
Maybe you can change/update/overwrite the middleware functionality.

You have to create your own middleware Class (see example) which checks in the config/admin.php
a new key "allowed_paths". This Key is from type "array".

Example config (config/admin.php): 

```
	//change this config to your own middleware defintions
	'middleware'              => ['admin.auth'],

	'allowed_path'			  => [
									'admin/links',
									'admin/products'
								],
```

Something like this:

```
<?php namespace SleepingOwl\Admin\Http\Middleware;

use AdminAuth;
use Closure;

class Authenticate
{

	/**
	 * Handle an incoming request.
	 *
	 * @param  \Illuminate\Http\Request $request
	 * @param  \Closure $next
	 * @return mixed
	 */
	public function handle($request, Closure $next)
	{
		if (AdminAuth::guest())
		{
			if ($request->ajax())
			{
				return response('Unauthorized.', 401);
			} else
			{
				return redirect()->guest(route('admin.login'));
			}
		}
               
                //in this example, I assume that in the table administrators is a flag "isAdmin",
                //but you can change it to whatever you can
		if( !AdminAuth::user()->isAdmin ) {
                        //here i check the current request path against the config definitions
			if(!in_array($request->path()), config('admin.allowed_paths') ) {
				return redirect()->intended(route('admin.wildcard', '/'));
			}
		}

		return $next($request);
	}

}

```

Hope this helps :)

**Comment by noxify** [comment]
Are you able to resolve your problem @netconception ?

**Comment by netconception** [comment]
I have another solution founded. 

So close!

Thanks for help!

**Comment by Elyahou** [comment]
Could you maybe present your solution ?
