### ISSUE TITLE
One to Many Relationsship in Form

### ISSUE THREAD

**Issue by netconception** [sleeping-owl/admin#118]
Hello,

current I use the dev version of owladmin.

Currently I have the following situation:

Table 1: questions
Table 2: questions_translations (via https://github.com/dimsav/laravel-translatable)

Now I want for my customer 1 form, who he can type in the question data and the questions.

Is that possible ?

I need only text fields.

Sorry for my bad english, I'm german!

**Comment by noxify** [comment]
Did you check https://github.com/sleeping-owl/admin/issues/103 ?

**Comment by netconception** [comment]
Yes, but I need it so, that the admin can edit all text fields, e.g. german, russian, english and so on .. the language of the admin panel is not important.

**Comment by netconception** [comment]
Example Form:

Position: 1 (question table)
German Text: Lorem Ipsum (question_translations table)
Russian Text: Lorem Ipsum (question_translations table)
French Text: Lorem Ipsum (question_translations table)

**Comment by netconception** [comment]
Any solution available?

**Comment by noxify** [comment]
Can you not use a tabbed form for this?
* One Tab for German
* One Tab for French
* One Tab for Russian

And inside of the each tab you will link to the different models?

**Comment by netconception** [comment]
Do you have an example for the tabbed solution ?

**Comment by noxify** [comment]
I have not exactly what you need :)

I have only the following scenarios.

I have to two modules, Categories and Products

Categories is based on the nested sets implementation with the baum/baum package.
In the Products module, I want to create a relation between One Product and X Categories.

For this I have created a many to many relation and my admin.php in the Products module looks like this:

```
Admin::model('Modules\Products\Entities\Product')->title('Products')->display(function ()
{
	$display = AdminDisplay::datatables();
	$display->columns([
		Column::string('id')->label('#'),
		Column::string('title')->label('Product Title'),
		Column::string('active')->label('Active'),
	]);
    return $display;

})->create(function ()
{ 
	$parent_categories 	= \Modules\Categories\Entities\Category::getNestedList('name', 'id', '-');

	$form = AdminForm::tabbed();
    $form->items([
        'General' => [
            FormItem::text('title', 'Title')->required(),
			FormItem::text('slug', 'Slug')->required(),
			FormItem::text('user_id', 'User')->required(),
			FormItem::ckeditor('description', 'Description')->required(),
			FormItem::checkbox('active', 'Active'),

        ],
        'Categories' => [
			
			FormItem::custom()->display(function ($instance)
			{
				$product_tree 		= \Config::get('products.default.category_tree');
			    return view('products::product_categories', compact('product_tree', 'instance'))->render();
			})->callback(function ($instance)
			{
				//while we creating a new product, we have to move the handling
				//for the categories in the Scrapbye\Providers\EventServiceProvider
				//This EventHandler will sync the categories after the create was successful
			})
        ],
    ]);
    return $form;

})->edit(function ()
{ 
	$parent_categories 	= \Modules\Categories\Entities\Category::getNestedList('name', 'id', '-');

	$form = AdminForm::tabbed();
    $form->items([
        'General' => [
            FormItem::text('title', 'Title')->required(),
			FormItem::text('slug', 'Slug')->required(),
			FormItem::text('user_id', 'User')->required(),
			FormItem::ckeditor('description', 'Description')->required(),
			FormItem::checkbox('active', 'Active'),

        ],
        'Categories' => [
			
			FormItem::custom()->display(function ($instance)
			{
				$product_tree 		= \Config::get('products.default.category_tree');

			    return view('products::product_categories', compact('product_tree', 'instance'))->render();
			})->callback(function ($instance)
			{
				//get selected categories
	            $categories             = explode(',', \Input::get('selected-categories'));
	            //remove # character from the array
	            array_pop($categories);
	            //add selected categories to the morph table
	            //and remove existing selection if they are not
	            //in the current categories array
	            $instance->categories()->sync($categories);
			})
        ],
    ]);
    return $form;
});
```

As you can see, I have for create and edit different definitions, because while creating a new product, I have no product id which is required to create a relationship. In the edit form, I can use the sync() functionality.

Now, to create a relationship after a successful product creation, I have created a new event which will sync the selected categories.

To do this, I have updated the `app / Providers / EventServiceProvider.php` 

My EventServiceProvider looks like this:

```
public function boot(DispatcherContract $events)
	{
		parent::boot($events);

	    ProductModel::created(function($product)
	    {

		    //get selected categories
            $categories             = explode(',', \Input::get('selected-categories'));
            //remove # character from the array
            array_pop($categories);
            //add selected categories to the morph table
            //and remove existing selection if they are not
            //in the current categories array
            $product->categories()->sync($categories);
	    });
	}
```

I don't know your database structure and how the relations are, but I think, with something like this you should be able to manage this.

P.S.: My code is for Admin V3

Greets from Germany ;) 
Marcus

**Comment by netconception** [comment]
I try to transfer this to my project:

I insert my question data and within the event handler I check, If some question is created and to then my action with the language ?

Right ?

**Comment by noxify** [comment]
Yes :)

**Comment by netconception** [comment]
Hey!

So now I have 2 tabbs, one for general data and one for the questions.

Definition:

    Admin::model('Politicaltest\Entities\Question')->title('Testfragen')->display(function ()
    {
        $display = AdminDisplay::datatables();
        $display->with('translations');
        $display->order(['1', 'asc']);
        $display->filters([

        ]);
        $display->columns([
            Column::lists('translations.name')->label('Country'),
            Column::string('position')->label('Position'),
            Column::custom()->label('Kurztest')->callback(function ($instance)
            {
                return $instance->short_test ? '&check;' : '-';
            }),
            Column::datetime('created_at')->label('Created_at')->format('d.m.Y H:i'),
            Column::datetime('updated_at')->label('Updated_at')->format('d.m.Y H:i'),
        ]);
        return $display;
    })->createAndEdit(function ()
    {
        $form = AdminForm::tabbed();
        $form->items([
            'Allgemeine Daten' => [
                FormItem::text('position', 'Position'),
                FormItem::checkbox('short_test', 'Short Test'),
            ],
            'Second Tab Label' => [
                FormItem::custom()->display(function ($instance)
                {
                    return view('admin.form.question_translate')->with('translations', $instance->translations)->render();
                })->callback(function ($instance)
                {
                })
            ],
        ]);
        return $form;
    });

So now I have 2 problems:

1.) How can I add a validation to my custom field ?
2.) The event handler for question:update only fires, when I update data from question model. But how can I fire the event, when I only edit the questions ?

Greetings.

**Comment by noxify** [comment]
Hi,

1) This should solve your problems: http://sleeping-owl.github.io/v3/en/Form.html 

```
FormItem::text('title')->required()->unique()->validationRule('my-custom-rule')
```

2) What do you mean exactly? If you want, drop me a mail to: webstone@gmail.com (Hangout is also available) then we can do some try & errors and if it's working, we can update the issue with the solution :)

Greets
Marcus

**Comment by netconception** [comment]
Hi Marcus,

I've add you in hangouts.

Problem 2 is finished.

But problem 1 is persistent.

First: I can't add a validation rule to a custom field. Here I get an error.

>Call to undefined method SleepingOwl\Admin\FormItems\Custom::required()

Second: How can I change the name of the field within the validation ?

Default he say "the field position is required". In Laravel I can change the field name via attriute names. How can I do that ?

**Comment by noxify** [comment]
No invite in hangout :(

**Comment by netconception** [comment]
Hm I readd you.
