### ISSUE TITLE
Tab View - Multiselect not working correctly in V3

### ISSUE THREAD

**Issue by noxify** [sleeping-owl/admin#119]
Hi,

I have a problem with the Multiselect inside a tabbed form.

* Without a tabbed form, the multiselect is working fine
* If the multiselect is on the first tab, the multiselect is working fine

If the multiselect is on the second tab, it will be shown with a incorrect width.

* OSX
* MAMP with PHP 5.6
* PostgresSQL
* Latest Google Chrome
![bildschirmfoto 2015-06-03 um 00 20 45](https://cloud.githubusercontent.com/assets/521777/7948690/bdfa07c4-0986-11e5-9046-6a2efbe0eb22.png)

Here is the code for the form 
```
$parent_categories = \Modules\Categories\Entities\Category::getNestedList('name', 'id', '-');
	

	$form = AdminForm::tabbed();
    $form->items([
        'General' => [
            FormItem::text('title', 'Title')->required(),
			FormItem::text('slug', 'Slug')->required(),
			FormItem::text('user_id', 'User')->required(),
			FormItem::ckeditor('description', 'Description')->required(),
			FormItem::checkbox('active', 'Active'),

        ],
        'Categories' => [
			FormItem::multiselect('categories', 'Categories')->options($parent_categories),            
        ],
    ]);
    return $form;
```

Thanks :)

**Comment by neverfan** [comment]
+1

**Comment by jcfreshu** [comment]
+1

It looks like the .chosen-container element went to width:0px for some reason.

**Comment by AgelxNash** [comment]
```javascript
$(function () {
    $('.chosen-container').width('100%');
});
```

**Comment by noxify** [comment]
Works perfect!
