### ISSUE TITLE
Возможность разбивать элементы формы на колонки

### ISSUE THREAD

**Issue by Denwebart** [sleeping-owl/admin#12]
Есть ли возможность ставить элементы формы в несколько колонок?
Каким образом можно отредактировать отображение формы?
Как вообще можно менять дизайн админки, можно ли натянуть свой шаблон, и как это сделать?

**Comment by sleeping-owl** [comment]
На отображение стандартных элементов сейчас повлиять никак нельзя (потому что я не вижу хорошего способа как это можно было бы сделать).

Как вариант можно создать кастомный элемент, который будет включать в себя несколько стандартных с дополнительным html-кодом (http://sleeping-owl.github.io/Form_Elements/Custom_Form_Elements.html).

Общий дизайн можно поменять, но верстку элементов, генерируемых динамически - нельзя.
Чтобы изменить общий дизайн нужно опубликовать view из пакета:
```bash
php artisan view:publish sleeping-owl/admin
```
И править файлы в `app/views/packages/sleeping-owl/admin`. Css-файл расположен в `public/packages/sleeping-owl/admin/all.min.css`.

**Comment by Denwebart** [comment]
Спасибо Вам большое.

**Comment by wiyfn** [comment]
Сделал вот такой рабочий роут: 
Route::get('/news/edit/{id}', 'Admin\NewsController@getEdit')->where('id', '[0-9]+');

    public function getEdit()
    {
        return view('admin.news.add');
    }

Отображается только содержимое файла add.blade.php. Как сделать что бы отображалась остальная часть страници (шаблона). Я понимаю что нужно использовать в таких ситуациях конструкцию @extend. Только не могу понять что туда писать нужно.

Отображает только при условии если роут прописаный в меню. В моем случаии нет.
