### ISSUE TITLE
Is there an easy way to have different fields on form create and edit

### ISSUE THREAD

**Issue by izzuco** [sleeping-owl/admin#123]
I have a situation where i need to show different fields for Form Create and Edit

**Comment by noxify** [comment]
Yes, 

V2:
http://sleeping-owl.github.io/en/Form_Elements/Custom_Form_Elements.html

V3:
http://sleeping-owl.github.io/v3/en/Form.html#custom

Hope this helps :)

**Comment by noxify** [comment]
If you're using V3 you can do the following:

```
<?php

/*
 * This is a simple example of the main features.
 * For full list see documentation.
 */

Admin::model('YourModel')->title('Model Title')->display(function ()
{
	//list columns

})->create(function ()
{
 	//create form fields

})->edit(function ()
{

	//edit form fields

});

```

For V2 you have to check the code

**Comment by izzuco** [comment]
That is awesome Thanks a lot
