### ISSUE TITLE
Validation: Custom Fields & Validation Messages

### ISSUE THREAD

**Issue by netconception** [sleeping-owl/admin#132]
Hi!

I have two question about the validation function.

1.) How can I change the validation messages and / or the validation attribute names ? Within default Laravel 5 function I can do this easiliy via messages or attribute function in form request
2.) How can I add a validation to a custom field with a custom view ? 

I use the current v3.

Greetings from Germany!

**Comment by netconception** [comment]
Solution done!

Thanks to @noxify

**Comment by Butochnikov** [comment]
What is the solution?

**Comment by johnshepherd** [comment]
Would you mind sharing the solution? Thanks.
