### ISSUE TITLE
Laravel 5.1 compatibility ?

### ISSUE THREAD

**Issue by Elyahou** [sleeping-owl/admin#135]
Is this package compatible with Laravel 5.1 that have LTS ?

Thank you

**Comment by netconception** [comment]
Hi @Elyahou,

yes it's compatible.

I use it with Laravel 5.1 and all seems okay!

Within "composer.json" you can see 

     "illuminate/support": "5.*",

That means, It's supported!

Greets from Germany.

**Comment by Elyahou** [comment]
Thank  you !

**Comment by MacedoRAC** [comment]
How can I install this package in L5.1?
