### ISSUE TITLE
Is there a due date to launch v3?

### ISSUE THREAD

**Issue by nunomazer** [sleeping-owl/admin#136]
Hi, 

amazing work on admin, I just started an application and where thinking in help with some improvements when saw the dev branch that already has almost everything I need.

My questions are:
1) do you have fixed a due date to launch v3? 
2) the actual state of v3 could be considered a beta or release candidate version?
2) being a Laravel developer, how could I help to get the v3 quickly stable?

**Comment by nunomazer** [comment]
Answered at #83

**Comment by nwrman** [comment]
@nunomazer, @sleeping-owl   I know this is closed, but I'm also about to use v3 on a project. And I was wondering exactly the same exact thing, how can I start contributing to this project?

**Comment by nunomazer** [comment]
Well, I'm thinking in contribute, first, translating the messages and docs to Brazilian Portuguese.
Next I'll start using it and try to fix bugs or implement some new things that can help my contexts of use, hoping this helps the community also.

**Comment by nwrman** [comment]
Great, I haven't thought about translating the docs into spanish. Though I already made a pull request to merge the language strings in to the development branch.

**Comment by nunomazer** [comment]
+1
