### ISSUE TITLE
Удаление связующих записей?

### ISSUE THREAD

**Issue by recew** [sleeping-owl/admin#138]
Доброго времени суток. Подскажите пожалуйска как реализировать удаление связующих записей?
Например если удаляется новость, то нужно удалить все коментарии к ней.

**Comment by Rikcon** [comment]
А вы можете это сделать с помощью связей БД 
ON DELETE CASCADE то что вам нужно.

**Comment by sleeping-owl** [comment]
Либо используя каскадное удаление на уровне БД, либо используя события Eloquent:
```php
protected static function boot()
{
	parent::boot();

	static::deleted(function ($instance)
	{
		// тут код удаления связанных записей, файлов и т.п.
	});
}
```
