### ISSUE TITLE
Нет возможности очистить поле с изображением

### ISSUE THREAD

**Issue by Denwebart** [sleeping-owl/admin#14]
1. Если хотя бы один раз пользователь загрузил изображение - то он не может полностью очистить поле image.
Ожидается, что рядом с картинкой будет крестик (кнопка) для очистки поля.

2. Название картинки после загрузки меняется. Это не очень хорошо для SEO. Название картинки немного помогает продвижению сайта. Хотелось бы, чтобы название картинки сохранялось, а проблему с одинаковым именем картинки можно было бы решить данной структурой папок:

```
{Название модели}/{id документа}/{название поля}/image.jpg
```

3. Не собираетесь ли Вы сделать ajax-загрузку изображения? Чтобы превью отображалось сразу после выбора (до сохранения). Было бы очень удобно.

Спасибо Вам большое.

**Comment by sleeping-owl** [comment]
Первый пункт сделал. Необходимо обновить пакет и опубликовать ассеты (с этим осторожней, если ты вносил изменения в стили или яваскрипт пакета):
```bash
php artisan asset:publish sleeping-owl/admin
```

По второму пункту возникают вопросы, необходимо более детально обдумать, возможно запланирую это.

Третий пункт в ближайшие планы скорее всего не попадет, так как это сильно меняет логику работы с изображениями, которая сейчас довольно прозрачна и усложнять не хочется.

**Comment by Denwebart** [comment]
Спасибо!

**Comment by sleeping-owl** [comment]
@Denwebart Добавил возможность называть загружаемые файлы по желанию. В массиве полей с изображениями теперь значения могут быть массивом. Первый элемент - директория, второй - замыкание, которое возвращает имя файла.
```php
public function getImageFields()
	{
		return [
			'image' => 'monuments/',
			'photo' => '',
			'other' => ['other_images/', function($directory, $originalName, $extension)
			{
				return $originalName;
			}]
		];
	}
```
