### ISSUE TITLE
[Question] Default language for Issues

### ISSUE THREAD

**Issue by noxify** [sleeping-owl/admin#141]
Hi guys,

I have a question to you: what you're thinking about that idea that we're using only english for new issues.
Currently we have a russian / english mix.

For me it's hard to understand what the russian characters mean - for me they are only hieroglyphics ;)

Maybe we can switch to english and everyone can help everyone.

If anyone has pro / cons for this idea let me know :)

Thanks & Greets
Marcus

**Comment by nunomazer** [comment]
+1

**Comment by netconception** [comment]
Hi @noxify,

+1 for you, german buddy :dancers: 

Greetz

**Comment by sleeping-owl** [comment]
I think russian-speaking users will not understand you. I'm trying to answer in english, but if the question was in russian I will answer in russian.
