### ISSUE TITLE
CKEditor Upload - Route [imagecache] not defined.

### ISSUE THREAD

**Issue by maximeparisse** [sleeping-owl/admin#147]
Hello,

I've an issue trying to use your module. I'm trying to upload an image with the CKEditor but i have this error showing up : "InvalidArgumentException in UrlGenerator.php line 276: Route [imagecache] not defined."

I've a fresh installation of Laravel 5.1, a fresh installation of your module. Just added a model "Article".

app/Article.php
```php
<?php
namespace App;
// use Illuminate\Database\Eloquent\Model;
class Article extends \SleepingOwl\Models\SleepingOwlModel
{
  protected $fillable = array('title', 'content');
}
```

app/admin/Article.php
```php
<?php
// Create admin model from User class with title and url alias
Admin::model('App\Article')
  ->title('Articles')
  ->as('articles')
  ->columns(function ()
  {
      Column::string('title');
      Column::string('updated_at');
  })
  ->form(function ()
  {
      FormItem::text('title', 'Title');
      FormItem::ckeditor('content', 'Content');
  });
```

And in my VerifyCsrfToken Middleware i've excluded the path for 'image/upload'

app/http/middleware/VerifyCsrfToken.php
```php
<?php
namespace App\Http\Middleware;
use Illuminate\Foundation\Http\Middleware\VerifyCsrfToken as BaseVerifier;
class VerifyCsrfToken extends BaseVerifier
{
    /**
     * The URIs that should be excluded from CSRF verification.
     *
     * @var array
     */
    protected $except = [
        'images/upload',
    ];
}
```

And I have this error
> InvalidArgumentException in UrlGenerator.php line 276:
> Route [imagecache] not defined.

Do you have an idea ?
PS: Sorry for my bad English ;-)

**Comment by vladprokopchuk** [comment]
same problem too...

**Comment by ryanall** [comment]
Have you added the correct configuration to config/imagecache.php - this solved the issue for me :)

**Comment by vladprokopchuk** [comment]
thx work

**Comment by progsmile** [comment]
'route' => 'imagecache' it helped in config/imagecache.php
