### ISSUE TITLE
Проверка на существование изображения

### ISSUE THREAD

**Issue by Denwebart** [sleeping-owl/admin#15]
Как делать проверку, загружено ли изображение к статье?
Ведь, если изображение не было загружено, то такая запись
```
$recipe->image->thumbnail('original')
```
вернёт неправильный путь
```
string(43) "http://diets.dev/img/cache/original/recipes"
```
А с помощью $recipe->image я не могу получить название загруженного изображения 
```
object(SleepingOwl\Models\Attributes\Image)#453 (2) { ["directory":protected]=> string(8) "recipes/" ["filename":protected]=> NULL }
```
Хотелось бы, чтобы если изображение не было загружено, $recipe->image->thumbnail('original') возвращал null.

**Comment by sleeping-owl** [comment]
Проверку можно сделать через
```php
$recipe->image->exists()
```
Также обновил код, `thumbnail()` теперь возвращает null, если изображения нет.
