### ISSUE TITLE
Orderable Model issue

### ISSUE THREAD

**Issue by HKGeeks** [sleeping-owl/admin#156]
Hello,

I try to add a orderable function to my project, but it having problem.
-. The first row should not appear the Move Up button
-. Number nine row cannot Move Down.

![image](https://cloud.githubusercontent.com/assets/5966527/8385981/2ac7e6e0-1c7f-11e5-94e1-d050b7a74e05.png)

Thank you for helping
John

**Comment by eugenem** [comment]
check this:
https://github.com/sleeping-owl/admin/issues/108

**Comment by HKGeeks** [comment]
thank you for your help, so do I need to upgrade the package to V3 to get the ordering feature?

**Comment by eugenem** [comment]
If you can upgrade to v3, it's much better that v2. But you'll have to redefine all models...

I remember that v2 was working with order fields as well, but there were some complications.

Check that order values in the DB start from 0

**Comment by HKGeeks** [comment]
Thanks, order values change to start from 0 is work!! Thank you very much!!!

**Comment by macedodebrito** [comment]
How are you adding a orderable function on the V2 ?

are you trying to adapt the V3 at the V2 ?
