### ISSUE TITLE
Error adding model to admin

### ISSUE THREAD

**Issue by jingyibo123** [sleeping-owl/admin#168]
Hi everyone,

I'm starting with this plugin and I'm having a little difficulty adding a model as a admin.
I've added a simple Poker model in the "App" folder, 

and I had this Poker.php in the folder admin:

``Admin::model('\Company')->title('Companies') ->with('contacts') ->columns(function (){`
`	Column::string('title', 'Title');`
`})->form(function ()`
`{`
`	FormItem::text('title', 'Title')->required()->unique();`
`});`

I got the error `*Class '\Company' not found.*`
if I change it to 
```Admin::model('\App\Company')->title('Companies')/* ->with('contacts') */->columns(function (){
...
});```

Then I got the error `*Cannot redeclare class Company*`
The same seem to work with de demo on laravel4.2 & admin 1.*
but I'm on laravel 5.1 admin 2.*
I would really appreciate with any help.

**Comment by klimsemenov86** [comment]
Try:
`Admin::menu(\App\Company::class);`

**Comment by jingyibo123** [comment]
Thanks a lot @klimsemenov86 ,
changing menu.php isn't giving anything different. 
I guess `('\App\Company')` and `(\App\Company::class)`  should be equivalent.
I guess there's something different in model defining since version 2.0?

**Comment by klimsemenov86** [comment]
I define model like this (laravel 5.1, last version of sleepingowl):

    namespace App;
    use SleepingOwl\Models\SleepingOwlModel;
    class Company extends SleepingOwlModel { ... }

**Comment by jingyibo123** [comment]
@klimsemenov86 
Thanks so much! I found the problem! Still a lot to learn!

**Comment by tldmic** [comment]
Hi Guys, I installed the latest SO package on L5.1 and followed guidelines provided on the SO site, I also have this problem. do I have to make a new folder called models at app/admin/models? and create companies/php as my model?,
