### ISSUE TITLE
Laravel 5

### ISSUE THREAD

**Issue by ANT0x1** [sleeping-owl/admin#17]
Будет ли поддержка Laravel 5? Если да, то как скоро?

**Comment by sleeping-owl** [comment]
Поддержка планируется. Пакет будет обновлен после выхода 5й версии.

**Comment by Malezha** [comment]
Laravel 5 вышел, ожидаем обновления =)

**Comment by sleeping-owl** [comment]
Пробуйте ветку пакета laravel-5 (https://github.com/sleeping-owl/admin/tree/laravel-5).
О найденных проблемах пишите, буду стараться править.

**Comment by sleeping-owl** [comment]
Произошло обновление репозитория.

Версия под 5й ларавел теперь в master ветке и начинается с версии пакета 2.0.0.

Версия под 4.2 ларавел перенесена в ветку `laravel-4.2` и будет по мере необходимости обновляться в 1.* версиях пакета.

Таким образом актуальные строки для `composer.json`:

Laravel 5:
"sleeping-owl/admin": "2.*"

Laravel 4.2:
"sleeping-owl/admin": "1.*"

**Comment by ANT0x1** [comment]
Есть небольшое замечание по readme к пакету.
В laravel 5, файл app.php был перенесен из "app/config/app.php" в "config/app.php". Пожалуйста, исправьте. :)

**Comment by sleeping-owl** [comment]
Обновил
