### ISSUE TITLE
Filter on multiselect

### ISSUE THREAD

**Issue by s6carlo** [sleeping-owl/admin#181]
Is it possibile for the user to "filter" the options in the Multiselect if there are many fields?

Otherwise a datatable have to be used to select them and build a a many to many relationship.
Thanks,
Carlo

**Comment by s6carlo** [comment]
In v3 it is available thanks to chosen. I am going to use it

**Comment by noxify** [comment]
@s6carlo is the bug resolved? If yes, maybe you can close it :)

**Comment by s6carlo** [comment]
Closed, solved in v3

**Comment by s6carlo** [comment]
Sol
