### ISSUE TITLE
Ошибка если в _token есть сочетание символов "AM" или "PM"

### ISSUE THREAD

**Issue by Denwebart** [sleeping-owl/admin#19]
При сохранении документа столкнулся с ошибкой, которая раньше не возникала.
```
'DateTime::__construct(): Failed to parse time string (T6FfUtR1CkKEYOrSAOzzvwcFWIpwyPxXxKDd2AMT) at position 1 (6): Unexpected character' in E:\Webprojects\diets\vendor\nesbot\carbon\src\Carbon\Carbon.php:192
```
Как выяснилось, она возникла из-за того, что значение ```_token``` определялось, как дата по наличию строке символов ```'AM'```.

Ещё, после очистки кук в браузере невозможно заново залогиниться, так как возникает ошибка:

```
Illuminate \ Session \ TokenMismatchException

Route::filter('csrf', function()
{
    if (Session::token() !== Input::get('_token'))
    {
        throw new Illuminate\Session\TokenMismatchException;
    }
});
```
Пришлось чистить поле remember_token в бд, чтоб залогиниться заново.

**Comment by sleeping-owl** [comment]
AM/PM проблему минимизировал, нужно будет дополнительно подумать как правильней решить эту задачу, но в большинстве ситуаций проблем возникать не должно.

С очисткой куков проблему воссоздать не смог, у меня ошибок не возникло. Опиши подробней порядок действий и браузер для воссоздания бага.

**Comment by Denwebart** [comment]
1. Залогиниться.
2. Разлогиниться.
3. Очистить куки за все время.
4. Попытаться залогиниться снова.

**Comment by sleeping-owl** [comment]
Я так понимаю это вполне нормальное поведение. То есть когда ты после разлогина попадаешь на страницу авторизации в сессию сохраняется значение, по которому csrf защита происходит. После этого ты удаляешь куки, тем самым и сессию обнуляя. При попытке авторизации срабатывает защита, потому что сессионное значение не совпадает. Если между 3 и 4 пунктом обновить страницу логина, то авторизация происходит нормально. Эта часть поведения ларавел никак не связана с моим пакетом.
