### ISSUE TITLE
How to override admin template?

### ISSUE THREAD

**Issue by xnhinzkyx** [sleeping-owl/admin#194]
Hello,

I been starting to use this package and can you help me how to override admin template? So that i have to add files in "resources/views/admin" folder instead of modifying files inside the vendor folder in SleepingOwl folder to be specific?

Thanks.

**Comment by noxify** [comment]
Hi,

you have to options to overwrite the existing admin template.

1. you can overwrite the views with "resources/views/admin"
2. Create your own template, a good example is the adminLTE theme: https://github.com/sleeping-owl/admin-lte-template

**Comment by xnhinzkyx** [comment]
I currently use adminLTE but I don't want to modify the files right in the vendor folder, how do I do that? 

Do you have any idea? or suggestions?

Thanks...

**Comment by acacha** [comment]
Adminlte package is a Laravel package. Read official docs about Laravel packages:http://laravel.com/docs/5.1/packages and how to override view files as noxigy suggest you at option 1. In this way you can override vuew files without touching anything at vendor folder

**Comment by xnhinzkyx** [comment]
Thanks to both of you noxify and acacha.  I tried what is said in the official docs but still don't work. I copy the files from the packages and modify it but nothings changed.

**Comment by acacha** [comment]
No idea then without more info sorry... If you can you will publish you code on github and then e can check you code to try to find the problem.

**Comment by xnhinzkyx** [comment]
I am using this V3 of admin package which I install in a fresh installation of Laravel 5.1 here
https://github.com/sleeping-owl/admin/tree/development

And I use the template https://github.com/sleeping-owl/admin-lte-template  and I want to override the view files of this template but I don't want to modify it directly which is inside the vendor/sleeping-owl/admin-lte-template

I would like to use the approach specified by noxify to add it in "resources/views/" and so on. Can you give me some example?

**Comment by noxify** [comment]
Hi,

I'm using https://github.com/barryvdh/laravel-debugbar to identify in which namespace the view to overwrite is
![bildschirmfoto 2015-08-05 um 21 19 11](https://cloud.githubusercontent.com/assets/521777/9095477/ac03155c-3bb7-11e5-9cd5-4de8f4113154.png)
 
This example shows the admin login page.
As you can see, there are two views:
1. admin-lte::default._layout.base
2. admin-lte::default.pages.login

Both views are currently package views.

Example: To overwrite the layout view with your own, you have to do the following:
1. Create a new directory named "admin-lte" in `/resources/views/vendor/admin-lte/default/`
(admin-lte is the namespace --> see screenshot above)
2. Create a directory named `_layout` and inside this folder you have to create a file named `base.blade.php`

With this way, you have to add each file manually - this is okay if you want to change only one or two files.
But if you want to change many things in the admin-lte theme you can do the following:

* Copy the `/vendor/sleeping-owl/admin-lte-template/src/views/default/*` to `/resources/views/vendor/admin-lte/default/`

or 

* Create a fork of the https://github.com/sleeping-owl/admin-lte-template package and update/rename the files/directories to your own

Hope this helps :)

**Comment by xnhinzkyx** [comment]
Great! now it works. Thanks @noxify for your great explanation and examples. Thank you guys.

**Comment by noxify** [comment]
you're welcome @xnhinzkyx - please don't forgot to close the issue ;)

**Comment by xnhinzkyx** [comment]
Ah yeah thanks :+1:
