### ISSUE TITLE
v3 - How to provide data to FormItem::select()

### ISSUE THREAD

**Issue by nateritter** [sleeping-owl/admin#197]
I want to provide an array of data to the `FormItem::select` method, but I don't want it to be all the data from a model - just a few things, by specifying the Ids of those things.  How would i accomplish this?

For instance, I have this:

```

Admin::model('App\Pick')->title('Picks')->display(function () {
    $display = AdminDisplay::datatables();
    $display->with('user', 'game', 'team');
    $display->filters([
        Filter::related('user_id')->model('App\User'),
        Filter::related('game_id')->model('App\Game'),
        Filter::related('team_id')->model('App\Team'),
    ]);
    $display->columns([
        Column::string('user.name')->label('User')
            ->append(Column::filter('user_id')),
        Column::string('game.id')->label('Game')
            ->append(Column::filter('game_id')),
        Column::string('team.team_name')->label('Team Picked')
            ->append(Column::filter('team_id')),
    ]);
    return $display;
})->createAndEdit(function () {
    $form = AdminForm::form();
    $form->items([
        FormItem::select('user_id', 'User')->model('App\User')
            ->display('name')->required(),
        FormItem::select('game_id', 'Game')->model('App\Game')
            ->display('id')->required(),
        FormItem::select('team_id', 'Team Picked')->model('App\Team')
            ->display('team_name'),
    ]);
    return $form;
});
```

In a "Game" there are two teams (a home team and an away team). In the line `FormItem::select('team_id', 'Team Picked')->model('App\Team')->display('team_name')`, I am pulling all the teams.  However, for this model, the user is predicting a winner, so I only want the two teams who are playing this game to be the options shown in the select.

Thoughts?

**Comment by nateritter** [comment]
Using the same code above, I have another couple questions.  

# For this prediction/pick, instead of showing the game_id, I want to show the two teams who are playing in the game.  How would I get that information to show in lieu of the game_id?

# Is it possible to create dependent drop-downs?  For instance, the teams would be dependent on the game.  And the game would be dependent on the week and season combo.  Any thoughts on how to do something like that?

**Comment by danpai88** [comment]
my english is not good,so i just guess  if want to solve your question,you may need to read the FormItem::select() document  ,  and it has a "options" method, hope to help U

**Comment by nateritter** [comment]
I figured it out.  I just needed to create and rename the relationship in laravel to something like awayTeam() and homeTeam() instead of team(), and then added a getFullTeamName() mutator, and then reference those instead.  Works like a charm.

As for the dependent dropdowns, it would be nice, but I just re-organized my app a bit better and didn't need that feature after all.
