### ISSUE TITLE
Error After Install

### ISSUE THREAD

**Issue by dberube** [sleeping-owl/admin#2]
After doing composer update and installing via editing config/app.php (Aliases and Providers), and then doing: php artisan config:publish sleeping-owl/admin

My entire app gets the following error:

PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /Users/david/Sites/neo.billing/app/admin/User.php on line 9
{"error":{"type":"Symfony\Component\Debug\Exception\FatalErrorException","message":"syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$'","file":"\/Users\/david\/Sites\/neo.billing\/app\/admin\/User.php","line":9}}

php artisan throws this as well -- any idea what's happening?

**Comment by patriciorasquetti** [comment]
Hi everyone, I'm Patricio from Argentina, sorry I know is been too long from the last post. I'm new in Laravel 5, and I'm having an exception when I try to excecute php artisan serve.
The problem appeared after trying to unsuccessfully install  compose require intervention/image, with the following error : Using version ^2.3 for intervention/image
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files

> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize

  [ErrorException]  
  The use statement with non-compound name 'Image' has no effect  

Script php artisan optimize handling the post-update-cmd event returned with an error

Installation failed, reverting ./composer.json to its original content.

  [RuntimeException]  
  Error Output: 

Now when I try to run php artisan serve, I get this error: (Please can anyone help me?)
  [Symfony\Component\Debug\Exception\FatalThrowableError]  
  Parse error: syntax error, unexpected ';', expecting identifier (T_STRING) or function (T_FUNCTION) or const (T_CONST) o  
  r \ (T_NS_SEPARATOR)

**Comment by patriciorasquetti** [comment]
does that wrong install have something to do with artisan server or is it just a typo? 
Thanks in advance.-
