### ISSUE TITLE
Multi-Filtering table

### ISSUE THREAD

**Issue by bololmon** [sleeping-owl/admin#21]
Hello. 
I'm using your plugin and I encounter the following problem: I have a travel table that contains the source, destination, date, etc etc. Default filtering searches all the fields from the table in question and I would like to implement a filtering more specific e.g. searchable only by origin and other destination, showing me the result whose destination and origin match my search. I've been testing and looking at documents from internet but say to use a different from yours plugin. 
Thank you for the attention.

**Comment by sleeping-owl** [comment]
Hello.
If you want each column to have its own filter input field - my library can`t do this. Maybe you can do this using custom columns (http://sleeping-owl.github.io/Columns/Custom_Columns.html), but it will be not so easy to do.

**Comment by sleeping-owl** [comment]
@bololmon Now you can do it. Update package to the latest version and publish assets (`php artisan asset:publish sleeping-owl/admin`). Add this to your model configuration:
```php
Admin::model('\MyModel')->columnFilter()->...
```
This will add filter input field to the bottom of each column.
