### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by AgelxNash** [sleeping-owl/admin#213]
For what reasons do not use pagination?

**Comment by MnMTech** [comment]
Pagination seems to have gone in v3. Is there a way to invoke this in the model config?

**Comment by MnMTech** [comment]
Change display to AdminDisplay::datatables()

**Comment by Spycomb** [comment]
See that,
http://sleeping-owl.github.io/v3/en/Displays.html

or use the datatablesAsync()
the
