### ISSUE TITLE
Пагинация

### ISSUE THREAD

**Issue by Denwebart** [sleeping-owl/admin#22]
Пагинация, как я понял, работает через JS. Она быстрая, это впечатляет.
Но я подозреваю, что уже примерно при 200 записях уже будет тормозить.
Что думаете по этому поводу?

**Comment by sleeping-owl** [comment]
В версии 1.2.0 добавилась возможность асинхронной загрузки данных. Для этого в конфигурации модели нужно указать:
```php
Admin::model('MyModel')->async()->...
```
И опубликовать ассеты:
```bash
php artisan asset:publish sleeping-owl/admin
```

**Comment by vanchelo** [comment]
@sleeping-owl в async режиме записи удаляются без подтверждения, только что случайно затер 2)) В обычном режиме подтверждение работает как положено!

**Comment by Denwebart** [comment]
После обновления появилась ошибка:
```
DataTables warning: table id=dataTable - Ajax error. For more information about this error, please see http://datatables.net/tn/7
```

**Comment by vanchelo** [comment]
И вот такой глюк появился после обновления до 1.2. Использую монгу, до обновление всё было норм.
![Глюк](http://i60.fastpic.ru/big/2015/0123/f3/ea6c52027893e289bfcd8ee4b282f9f3.png)

**Comment by sleeping-owl** [comment]
@vanchelo я так понимаю это из-за того, что теперь поверх query builder`а работает мой пакет with-join, который позволяет сортировку и поиск по связанным полям делать. Собственно это основная проблема почему изначально асинхронного вывода не было. Какое на твой взгляд адекватное решение, поскольку я другими субд не пользуюсь? Я мог бы просто сделать отключаемым этот функционал.

**Comment by sleeping-owl** [comment]
@Denwebart как я понял все модели перевел в асинхронный режим, но только одна после этого перестала работать? Что в ней есть особенного? Какие-то особые связи, фильтры, столбцы? Можешь показать ее конфиг?

**Comment by sleeping-owl** [comment]
@vanchelo удаление без подтверждения пофиксил

**Comment by vanchelo** [comment]
@sleeping-owl для монги просто так сортировку по связанным данным не запилить, по крайне мере в том пакете который я юзаю, а составлять сложные запросы к монге "руками" и чтобы это было универсально в админке мне кажется сложной задачей. Поэтому сделать отключаемым данный функционал будет нормальным решение. =)

**Comment by sleeping-owl** [comment]
@vanchelo обнови пакет и в конфигурацию модели добавь
```php
Admin::model('Mymodel')->disableWithJoin()->...
```
это должно решить твою проблему, отключает сортировку и фильтрацию по связанным записям

**Comment by Denwebart** [comment]
Я нашёл причину. Закомментировал строку
```Column::string('category.menu_title', 'Категория');```
И всё работает.

**Comment by sleeping-owl** [comment]
@Denwebart странное поведение, связанные сущности у меня асинхронно выводятся нормально. а если посмотреть сетевую активность браузера, там на запрос данных сервер должен ответить ошибкой. что за ошибка?

**Comment by Denwebart** [comment]
```
"Illuminate\Database\QueryException"
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'category.menu_title' in 'order clause' (SQL: select `diets`.* from `diets` order by `category`.`menu_title` asc limit 10 offset 0)
E:\Webprojects\diets\vendor\laravel\framework\src\Illuminate\Database\Connection.php
Line 625
```

**Comment by sleeping-owl** [comment]
@Denwebart ты используешь eager loading? Судя по ошибке - нужно добавить в конфигурацию модели:
```php
Admin::model('MyModel')->...->with('category')->...
```
чтобы связанные данные подгружались одним запросом

**Comment by Denwebart** [comment]
Добавил, заработало. Была версия 1.2.1
Сразу после того, как заработало, решил обновить композер. Сейчас версия админки - 1.2.3.
Опять перестало работать. Вот мой код:
```
Admin::model(\Diet::class)->async()->title('Диеты')->with('category')->filters(function ()
{

})->columns(function ()
{
	Column::string('category.menu_title', 'Категория');
	Column::string('title', 'Заголовок');
//	Column::string('alias', 'Алиас');
//	Column::string('image', 'Изображение');
//	Column::string('image_alt', 'Альт для изображения');
//	Column::string('meta_title', 'Мета-тег Title');
//	Column::string('meta_desc', 'Мета-тег Description');
//	Column::string('meta_key', 'Мета-тег Keywords');
//	Column::string('content', 'Контент');
	Column::string('is_published', 'Статус публикации');
	Column::string('views', 'Просмотры');
	Column::string('votes_like', 'Нравится');
	Column::string('votes_dislike', 'Не нравится');
	Column::string('comments_number', 'Комментарии');
	Column::date('created_at', 'Дата создания')->format('medium', 'short');
	Column::date('updated_at', 'Дата обновления')->format('medium', 'short');
	Column::date('published_at', 'Дата публикации')->format('medium', 'short');
})
```

**Comment by sleeping-owl** [comment]
@Denwebart обнови еще раз композер, теперь должно работать

**Comment by Denwebart** [comment]
Работает, спасибо!

**Comment by antonim** [comment]
Добрый день. Столкнулся с такой проблемой: хочу в пыйджинг впихнуть асинхронную загрузку фотографий. Это очень удобно. Но: 
1. Я не нашел как добавить скрипт и стили на конкретный ютраницу пагинации , пришлось пихать прям в бутстрапе: 
AssetManager::addStyle('/packages/dropzone/dropzone.css');
AssetManager::addScript('/packages/dropzone/dropzone.js');

2. Главная проблема в том, что после перезагрузки страницы после перелистывания, сортировки и т.д. естественно перестает работать плагин. С плагином можно разобраться, если бы было событие о том, что страница перегрузилась... как бы его получить подскажите?

**Comment by strotmann** [comment]
Покажите пример как реализовать фильтр ! спасибо)
