### ISSUE TITLE
initial admin controller in subfolder

### ISSUE THREAD

**Issue by ukadev** [sleeping-owl/admin#221]
Hello,

I want to have my AdminController in /app/Http/Controllers/Back/AdminController but there is no way to do it work with this admin panel inside menu.php.

I tried the above code assuming the package is loading the default controllers folder:
Admin::menu()->url('/')->label('Start page')->icon('fa-dashboard')->uses('\Back\AdminController@getIndex');

any ideas?

Regards.

**Comment by bihlmaierh** [comment]
Hello @ukadev,

please test the following line: 
`Admin::menu()->url('/')->label('Start page')->icon('fa-dashboard')->uses('App\Http\Controllers\Back\AdminController@getIndex');`

**Comment by bihlmaierh** [comment]
Hello @ukadev,

you need to extend the orginal admin controller from soa and then u need to load it within app configuration.

**Comment by Spycomb** [comment]
or.. render it manually
with 
<code>
  $data = view('viewName',($dataToPassToTheView));
  return Admin::view($data, 'The Title');
</code>

see this look at the note at the very bottom of the content section  ( notice that it uses the v3 of Sleeping Owl Admin)
http://sleeping-owl.github.io/v3/en/Getting_Started/Routes_Configuration.html
