### ISSUE TITLE
Force menu refresh - render

### ISSUE THREAD

**Issue by s6carlo** [sleeping-owl/admin#229]
Hi,
 in my application I have to hide/show menu items on the base of a session variable, called "site".

I use a link  **admin/site/1** to set the variable, this link is managed by a route 
```php
Route::get('/site/{id}', function($id)
{
    Session::put('site', $id);
    return Admin::view((View::make('admin.home')),"Title");
}
```
In my menu.php file I have
```php
$site =  Session::get('site', '0');
if ($site==1) {
}
....

```

The problem is that after the link   **admin/site/1** is clicked the menu does not change according to the menu.php file, after a click in a menu item it changes. Is there a possibility to force menu render in the from route.php file?

Thanks,
 Carlo

**Comment by acacha** [comment]
I Carlo,

I'm also interested in this because I think a previous issue is related: https://github.com/sleeping-owl/admin/issues/226. Please let me know if you found a solution.

**Comment by s6carlo** [comment]
In my case the problem is due to the session variable managment, the session variable is actually updated aftert the view render. 

Is it possibile to set a variable, related to user, through a link ? In this case I will not use session variable.

**Comment by acacha** [comment]
@s6carlo did you see https://github.com/sleeping-owl/admin/issues/226 ?

I think you can put the code that updates session variable at start of file menu.php

**Comment by s6carlo** [comment]
@acacha Thanks, solved even if not in the best way.
I moved the "route" command inside the menu.php file, in this way I have the new session variable (id) from the url and I can change the menu even if it is not already stored in the session.

Carlo

**Comment by s6carlo** [comment]
The best solution is something like the two buttons used to change layout [in the v3 demo] (sleepingowladmindemo2.cloudcontrolled.com) Web Login does not work, you have to download and installa the demo locally.

In short the button call a route with a parameter and in route.php 
```php
Route::get('/template/{template}', [
	'as' => 'admin.change-template',
	function ($template)
	{
		if ($template == 0)
		{
			$cookie = cookie('admin-template', $template, -1);
		} else
		{
			$cookie = cookie('admin-template', $template);
		}
		return back()->withCookie($cookie);
	}
]);

```
