### ISSUE TITLE
Class 'SleepingOwl\WithJoin\WithJoinEloquentBuilder' not found

### ISSUE THREAD

**Issue by alexkonstantin** [sleeping-owl/admin#23]
Модель:

    <?php
    use SleepingOwl\Models\SleepingOwlModel;
    class SiteGame extends SleepingOwlModel {

меню:

    Admin::menu('\SiteGame');;

bootstrap:

    Admin::model('\SiteGame')->title('Games on site')
    ->columns(function ()
    {
        Column::string('name', 'Name');
    })
    ->form(function ()
    {
        FormItem::text('name', 'Name')->required()->unique();
    });

ошибка:

    Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_ERROR) 
    Class 'SleepingOwl\WithJoin\WithJoinEloquentBuilder' not found
    Open: .../vendor/sleeping-owl/admin/src/SleepingOwl/Admin/Repositories/ModelRepository.php
	 * @param null $params
	 * @return array
	 */
	public function tableData($params = null)
	{
		$baseQuery = $this->instance->newQuery()->getQuery();
		/** @var WithJoinEloquentBuilder $query */
		$query = new WithJoinEloquentBuilder($baseQuery);
		$with = $this->modelItem->getWith();
		$query->setModel($this->instance)->with($with);

**Comment by sleeping-owl** [comment]
Попробуй выполнить `composer update`. В последней версии добавилась новая зависимость у пакета и судя по ошибке этот пакет почему-то у тебя не был скачан, но пытается использоваться. Как вариант решения проблемы - добавить в composer.json в зависимости пакет "sleeping-owl/with-join" версии "1.*".

**Comment by alexkonstantin** [comment]
Да заработало после composer update была заменена версия 1.2.1 на 1.2.2
