### ISSUE TITLE
Error in BaseFormItem.php line 41

### ISSUE THREAD

**Issue by AntonBenediuk** [sleeping-owl/admin#231]
I did update to last version(version 3) and then I cant work with packege. This is error:
FatalErrorException in BaseFormItem.php line 41:
syntax error, unexpected '{'

Whats problem?Please help

**Comment by Muffassa** [comment]
You have unexpected ''{' in line 41 of BaseFormItem. You have to delete this ''{" from 41 line.

**Comment by AntonBenediuk** [comment]
I understand, butt I dont work in this file. I think its problem in package, because not problem before composer update

**Comment by johnshepherd** [comment]
See #227

**Comment by markioooo** [comment]
Hello, Can this be fixed in the package please? There is a plus before lines 41, 42, 43 causing the error message. Thanks!
