### ISSUE TITLE
How to getTimeStamps?

### ISSUE THREAD

**Issue by vektrom** [sleeping-owl/admin#24]
Hello, 

I created the "getTimeStamps" class in the model, but when editing from SleepingOwl the date and time are not inserted.

I used this line of code (app/admin/usuari.php).
```PHP
FormItem::timestamp('fecha_inscripcion', 'Data inscripció');
```

And this is my code from the model (app/models/Usuari.php).
```PHP
public function getTimeStamps() {    
    return array_merge(parent::getTimeStamps(), ['fecha_inscripcion']);
 }
```

If I use the function getDates it only update the Time but not the Date:
```PHP
public function getDates() {    
    return array_merge(parent::getDates(), ['data_naixement','fecha_inscripcion']);
}
```
What can I do to make it work?

Thank You.

**Comment by sleeping-owl** [comment]
There is no method `getTimeStamps()` in my package. `getDates()` includes both date and timestamp field types. The possible problem is your timestamp format. Please paste your timestamp sample here.

**Comment by vektrom** [comment]
This is a sample of a timestamp of my database:

```
2015-01-29 11:30:56
```

Thanks for answering.

**Comment by sleeping-owl** [comment]
Update package to the latest version (via `composer update`). This update will fix the bug.

**Comment by sleeping-owl** [comment]
@vektrom Update fix your problem?

**Comment by vektrom** [comment]
Yes, your update fix this problem.
Thank you so much.
