### ISSUE TITLE
События модели не вызываются

### ISSUE THREAD

**Issue by alexkonstantin** [sleeping-owl/admin#25]
Добрый день скажите почему могут не вызываться события у модели?

   SiteGame::updating(function($model)
    {
                ...
    });

пробовал и через boot

    public static function boot()
    {
        parent::boot();
        static::updating(function($model)
        {
                ...
        });

    }

**Comment by sleeping-owl** [comment]
Добавил такой код в модель:
```php
public static function boot()
{
	parent::boot();
	static::updating(function($model)
	{
		dd($model);
	});
}
```
При редактировании записи событие сработало как положено. Возможно ты не то событие тригеришь? Я имею в виду, что `updating` вызывается только при редактировании, но не работает при добавлении.
Есть ли какие-то особенности в модели? Потому что я экспериментировал на модели из моего примера, а она довольно простая.

**Comment by alexkonstantin** [comment]
извините, все заработало, просто если не меняешm данные в форме то и событие в модели не вызывается, а при изменение вызывается. мой косяк еще только изучаю laravel
