### ISSUE TITLE
Override main query in CRUD.

### ISSUE THREAD

**Issue by mapeveri** [sleeping-owl/admin#254]
How I can override main query in crud?. This query is he is the one who gets the data in the grid.

Thanks!

**Comment by mapeveri** [comment]
I resolved like this:

Add this method to the model:

public function newQuery(){
      $query = parent::newQuery();
      return $query->where(My Filter...);
      return $query;
}

**Comment by greedchikara** [comment]
hey dude can you explain it a little more. i want to some certains row from a table, how can i achieve that.
Any help will be aprreciated.

**Comment by mapeveri** [comment]
@greedchikara I'll show you what I did:

   public function newQuery(){
         $query = parent::newQuery();
         if(AdminAuth::user()['st_administrador'] != "1"){
            $data = PermisoUsuario::where('idUsuario', '=', AdminAuth::user()->id)->lists('idProyecto')-   >all();
             if(empty($data)){
                $where = "id_proyecto";
           }else{
                $where = "id_proyecto IN(" . implode(',',$data) . ")";
           }
           return $query->whereRaw($where);
        }else{
           return $query;
        }	
   }

I needed if it is not Administrator get back all the records, but filter by users permissions. My main query is $query->whereRaw(...).

I hope it helps you.

**Comment by greedchikara** [comment]
thats man, this helped
