### ISSUE TITLE
Routing in custom controllers

### ISSUE THREAD

**Issue by vkosachev** [sleeping-owl/admin#26]
Hi, I've wanted to use a custom controller in the admin panel. It seems that I can only route to the  action specified in  menu configuration. If I create an url to my controller from the view, I cannot get to the action.

For example :
```PHP
Admin::menu()->url('claims')->label('Claims')->icon('fa-money')->uses('\Controllers\Dashboard\ClaimController@getIndex');
```

Then, in my action I render a view. From that view I try to provide a link to another method in that controller:

```PHP
<a class="btn btn-success btn-sm" href="{{action('\Controllers\Dashboard\ClaimController@getInfo', $claim->id)}}">
```
First it said that it cannot find the route, so i thought that adding a specific route to my **routes.php** would do the trick, but it sill ignores that : 
```PHP
Route::group(['prefix' => 'admin', 'before' => 'admin.auth'], function ()
	{
		Route::controller('claims', '\\Controllers\\Dashboard\\ClaimController');
	});
```

The main question is how to use the routing inside the custom controller. Thx

**Comment by sleeping-owl** [comment]
Now you can use the following style (update to the latest version):

Create hidden menu item for your controller action (this will register necessary route without menu item):
```php
Admin::menu()->url('subdir/demo')->uses('AdminController@getThird')->hidden();
```

Use this code to get full url:
```php
route('sleeping-owl-admin.wildcard', 'subdir/demo')
```

This will require menu item for every action you want to use.
Is this enough to solve your problem?

**Comment by vkosachev** [comment]
Well,  seems that problem persists, i tried to provide an id to that route, and it still points  me as missing ( I have updated the package), I tried the following :
```PHP
Admin::menu()->url('claims/info/{id}')->hidden()->uses('\Controllers\Dashboard\ClaimController@getInfo');
```
or

```PHP
Admin::menu()->url('claims/info')->hidden()->uses('\Controllers\Dashboard\ClaimController@getInfo');
```

and the route: 
```PHP
route('sleeping-owl-admin.wildcard', 'claims/info/'.$claim->id)
```

Am I doing it right?

**Comment by vkosachev** [comment]
Can you add the posibility to use the routes from the main router file? maybe this would be simpler?

**Comment by sleeping-owl** [comment]
Update package to the latest version, install my `route-priority` package (https://github.com/sleeping-owl/route-priority) and you will be able to use your own routes from `routes.php`.

With this package installed my wildcard route will have the lowest priority and your own routes will work.

Use `Admin::view($content, $title = null)` method to render your view inside of administrative interface:
```php
Route::get('/admin/my_test', function()
{
	$content = 'hello';
	$title = 'my own title';
	return Admin::view($content, $title);
});
```

**Comment by vkosachev** [comment]
Yeah, this seem to be working now, though I had to specify the highest priority for custom routes in my **routes.php** explicitly and grouping in this case didn't work(or I didn't get how to specify the priority to the whole group).  Could you please specify also what can be rendered as ```$content``` ? whole html? Thx.

**Comment by sleeping-owl** [comment]
I\`ve updated `route-priority` package. Now you can set priority to the group by:
```php
Route::group(['prefix' => 'my-prefix', 'priority' => 100], function ()
{
	Route::get('first-route', function (){});
	Route::get('second-route', function (){});
});
```

`$content` is html you want to display within `<div id="page-wrapper">`.

**Comment by vkosachev** [comment]
Really cool, thx for your support :+1:
