### ISSUE TITLE
Изменение изображений при сохранении

### ISSUE THREAD

**Issue by Malezha** [sleeping-owl/admin#27]
Было бы неплохо добавить возможность использовать функционал Intervention Image при загрузке изображения.

**Comment by sleeping-owl** [comment]
На данный момент это можно реализовать определив метод `setImage` в модели:
```php
public function setImage($field, $image)
{
	parent::setImage($field, $image);
	$file = $this->$field;
	if ( ! $file->exists()) return;
	$path = $file->getFullPath();
	Image::make($path)->resize(10, 10)->save();
}
```

**Comment by Malezha** [comment]
Может тогда включить этот метод в документацию? Все же изменение изображения при загрузке достаточно частая операция.
