### ISSUE TITLE
Conditions in tree view

### ISSUE THREAD

**Issue by diffmike** [sleeping-owl/admin#273]
Can I change query for tree view?
Like in table view:

```
$display->apply(function ($query)
{
    $query->where('my_field', 2);
    $query->orderBy('date', 'desc');
});
```

**Comment by noxify** [comment]
Hi,

you can use the code from our forked version :)

https://github.com/Pseudoagentur/soa-sentinel/blob/develop/src/SleepingOwl/Admin/Display/DisplayTree.php

We have implemented the `apply()` and `scope()` functionality.
