### ISSUE TITLE
Laravel 4.2 admin:install permission denied

### ISSUE THREAD

**Issue by HardTacos** [sleeping-owl/admin#28]
I am trying to install using Laravel 4.2
I have added the facades and the service providers, as well as adding the dependency to composer.js

When I run:
`php artisan admin:install` 

The first migration occures, but the second one fails, responding with a
`[ErrorException] - mkdir(): Permission Denied` error.

Is there something that I am missing?

Thanks!

**Comment by sleeping-owl** [comment]
It seems like your php configuration can\`t create directories. You can check permissions for project directories or manually create necessary directories:
- `app/admin`
- `public/images/uploads`
- `public/files`

and run `admin:install` command again. Public directories must be writeable for php.
