### ISSUE TITLE
query exception, adminitrator

### ISSUE THREAD

**Issue by n7best** [sleeping-owl/admin#289]
for 75% of the request I got QueryException in Connection.php line 651:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'homestead.administrators' doesn't exist (SQL: select `administrators`.* from `administrators` where `administrators`.`id` = 1 limit 1). and 25% time it went through, any idea?

this is brand new installation with latest laravell

**Comment by jadjoubran** [comment]
You need the administrator table for the package to work 

Run `artisan vendor:publish`
Then `artisan migrate`

**Comment by n7best** [comment]
@jadjoubran yea, I already did that and setup few model with the system and everything work fine. ONLY it work 25% of time.

**Comment by jadjoubran** [comment]
Are you on Windows?

**Comment by n7best** [comment]
@jadjoubran I am using mac, the test site is running with laravel homestead with vagrant, pretty weird problem. I can saw the table is there and all other table is fine.

**Comment by n7best** [comment]
restart the computer solved it.
