### ISSUE TITLE
Не появляется кнопка "редактировать" на странице модели

### ISSUE THREAD

**Issue by AngryGantz** [sleeping-owl/admin#303]
Определение модели простейшее:

```php
Admin::model('\App\Models\MenuitemType')->title('Типы пунктов меню')->display(function ()
{
	$display = AdminDisplay::datatables();
	$display->with();
	$display->filters([
	]);
	$display->columns([
		Column::string('name')->label('Name'),
		Column::string('id')->label('Id'),
	]);
	return $display;
})->createAndEdit(function ()
{
	$form = AdminForm::form();
	$form->items([
		FormItem::text('name', 'Name'),
	]);
	return $form;
});
```
На странице в строках списка кнопка удаления есть, а кнопки редактирования нет. 
В чем проблема? Что не так?  Что надо сделать, что-бы получить возможность редактирования записи? 
![prscr](https://cloud.githubusercontent.com/assets/2835190/11880228/38bd4fc6-a508-11e5-8989-f6e7bfad7a23.png)

**Comment by AngryGantz** [comment]
Решил вопрос.

**Comment by strotmann** [comment]
Подскажите а где можно почитать какие есть icon()? И куда надо их грузить(в какую папку ) что бы добавить новые? Спасибо)

**Comment by ariyDez** [comment]
AngryGantz, как вы решили этот вопрос? Та же самая проблема?

**Comment by Deviator2001** [comment]
У меня такая проблема возникла из-за нижнего регистра первой буквы в названии модели! Sleeping Owl чувствителен к этому. Следите за соответствием регистров букв в названиях моделей.

**Comment by ariyDez** [comment]
Спасибо.. что хоть кто-то отозвался :)

31 мая 2016 г., 12:49 пользователь Deviator2001 notifications@github.com
написал:

**Comment by suroviy** [comment]
Кнопка так и не появляется вот пример секции
https://gist.github.com/suroviy/c2ea8f3ccc59fd55d765e4f6e7685953

**Comment by Fedchishina** [comment]
Тоже была такая проблема. Будьте аккуратны и с namespace!

в моей созданной модели был прописан не тот namespace
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Section extends Model
{
    protected $table = 'sections';
    protected $fillable = [
        'name'
    ];
}
 namespace App\models; - было
 а надо:
namespace App\Models;

**Comment by phpner** [comment]
О! Блин! Спасибо!
