### ISSUE TITLE
Call to undefined method Illuminate\Database\Query\Builder::getPresentationFileAttribute()

### ISSUE THREAD

**Issue by fatalstrike** [sleeping-owl/admin#31]
В модели есть поле для загрузки файла:
```
protected $fillable = ['presentation_file'];
```

Настраиваю модель для работы с файлам по документации, по при открытии формы создания в админке вылетает исключение:

```
Call to undefined method Illuminate\Database\Query\Builder::getPresentationFileAttribute() 
(View: C:\OpenServer\domains\project.dev\vendor\sleeping-owl\admin\src\views\model\form.blade.php)
```

**Comment by sleeping-owl** [comment]
Обнови пакет до последней версии, там я исправил этот баг. Проблема была в подчеркивании в названии поля, теперь это не должно больше влиять на работоспособность.
