### ISSUE TITLE
Class 'SleepingOwl\Models\SleepingOwlModel' not found

### ISSUE THREAD

**Issue by budeci** [sleeping-owl/admin#317]
laravel/framework": "5.0.*",
"sleeping-owl/admin": "dev-development",
"sleeping-owl/admin-lte-template": "dev-master",

[My model](http://joxi.ru/82Q7Z3VS14LXZr)

**Comment by KMDSOUF** [comment]
Hi,
You must update vendor before runing SleepingOwl install command.

1- $ composer self-update
2- $ composer update
3- $ php artisan vendor:publish
4- $ php artisan admin:install
