### ISSUE TITLE
Problem with Timestamp FormItem

### ISSUE THREAD

**Issue by SubniC** [sleeping-owl/admin#32]
Hi, first thank you for this great package I just start playing with it, but it looks very nice.

I'm having a validation problem with some timestamp fields on a model, when I try to save it I always get a validation error saying "The DATE_FIELD is not a valid date."

The site is Spanish so it is using Spanish date format, so in the frontend form I can see the picker and the date are sent back to the server with the format "d/m/Y H:i"

```
------WebKitFormBoundaryCE36NbwdAdXEa6OP
Content-Disposition: form-data; name="fecha_inicio"

12/02/2015 20:42
------WebKitFormBoundaryCE36NbwdAdXEa6OP
Content-Disposition: form-data; name="fecha_fin"

13/02/2015 20:42
------WebKitFormBoundaryCE36NbwdAdXEa6OP--
```

The validation result:

![Validation result](http://i58.tinypic.com/2d0b68n.png)

I guess the problem is with the built-in validation, the Admin uses Laravel's date validation and it uses strtotime to transform the input, but strtotime is not working with the date format because it confuses the month with the day, so from 13th date is considered invalid.

Is there already a method to deal with date format validation?

I'm using the Laravel 4.2 branch.

Thanks!

**Comment by sleeping-owl** [comment]
Update package to the latest version (1.3.6 for laravel 4.2) and try it. I hope this will fix the problem.

**Comment by SubniC** [comment]
Thanks for your answer, i've updated (i was on version 1.3.4) but now I'm getting this error:

![Locale offset error](http://i61.tinypic.com/24q4ghu.png)

**Comment by sleeping-owl** [comment]
Please try again with the latest version

**Comment by SubniC** [comment]
Thanks! with version 1.3.7 is working fine :)

**Comment by mapeveri** [comment]
@SubniC How you did to put the date format in Spanish?. Thanks!

**Comment by SubniC** [comment]
@mapeveri I just set in the app/config/app.php the field *timezone* to *Europe/Madrid* and the field *locale* to *es*, the magic happens under the hood.

**Comment by mapeveri** [comment]
@SubniC thanks, it worked :+1:
