### ISSUE TITLE
Issue showing spanish date on datatable

### ISSUE THREAD

**Issue by SubniC** [sleeping-owl/admin#33]
I'm having another date issue, this time is in the javascript/datatables side, when I try to show the date on my model list it breaks JS code and throw an error to the console, the screenshot shows how the datatable is not being fully loaded and the console error.

![Error with date on datatables](http://i60.tinypic.com/2mhy520.png)

I'm using Laravel 4.2 with Admin 1.3.7.

Once again thank you very much.

**Comment by sleeping-owl** [comment]
Update package and execute the following command to fix this problem:
```bash
php artisan asset:publish sleeping-owl/admin
```

**Comment by SubniC** [comment]
It is fixed :) thank you very much.

I've a question, is it possible to open the creation form with some preloaded values on the fields?

The intention is, with an acction on a datatable open another creation form, this form should have some of the creation form fields with values.

**Comment by sleeping-owl** [comment]
You can't do it now, but I like this idea. I will try to add this feature in a few days.

**Comment by SubniC** [comment]
thanks!!! that is great :)

**Comment by sleeping-owl** [comment]
Now you can set default value for every form item (http://sleeping-owl.github.io/en/Form_Elements/Overview.html):
```php
FormItem::text('firstName', 'First Name')->required()->default('John');
FormItem::text('lastName', 'Last Name')->required()->default('Doe');
FormItem::date('birthday', 'Birthday')->default('10/10/2002');
```
