### ISSUE TITLE
Call to undefined method Illuminate\Database\Query\Builder::validate()

### ISSUE THREAD

**Issue by stevenmaguire** [sleeping-owl/admin#36]
I encounter this issue when using the default CRUD screens to create a new entity for the given model. Is this related to compatibility with L5?

**Comment by sirikkoster** [comment]
I have the same problem, did you resolved it ?

**Comment by sleeping-owl** [comment]
There are 2 ways to solve it (http://sleeping-owl.github.io/en/Getting_Started/Validation.html):
1. Extend your models from `SleepingOwl\Models\SleepingOwlModel`
2. Implement `SleepingOwl\Models\Interfaces\ValidationModelInterface` interface in your models

**Comment by stevenmaguire** [comment]
@sirikkoster I closed this issue originally because I used solution 1 from @sleeping-owl suggestions.
