### ISSUE TITLE
InstallCommand::handle() does not exist

### ISSUE THREAD

**Issue by antonkomarev** [sleeping-owl/admin#363]
Hello guys!

I've tried to install sleeping owl with command `php artisan sleepingowl:install` but got output:

> ReflectionException: Method SleepingOwl\Admin\Console\Commands\InstallCommand::handle() does not exist

Happens on Laravel 5.6 clean install. Using `"laravelrus/sleepingowl": "4.*@dev"` dependency.

**Comment by antonkomarev** [comment]
If add `handle` method which will call `runInstaller()` under the hood then output:

> Symfony\Component\Debug\Exception\FatalThrowableError  : Type error: Argument 2 passed to SleepingOwl\Admin\Console\Installation\Installator::__construct() must be an instance of Illuminate\Config\Repository, null given, called in /media/ell/DATA/Projects/stroi/stroi/vendor/laravelrus/sleepingowl/src/Console/Commands/InstallCommand.php on line 40

**Comment by Butochnikov** [comment]
ставь https://github.com/LaravelRUS/SleepingOwlAdmin 

composer require laravelrus/sleepingowl:dev-dev или new

**Comment by antonkomarev** [comment]
Спасибо. Прошу прощения, не в том репозитории issue создал, попробую ещё раз, если что в правильном месте буду писать :)
