### ISSUE TITLE
Declaration of SleepingOwl\Models\SleepingOwlModel::newFromBuilder() should be compatible with Illuminate\Database\Eloquent\Model::newFromBuilder($attributes = Array, $connection = NULL)

### ISSUE THREAD

**Issue by DionisioFG** [sleeping-owl/admin#37]
Hi!

Today I ran composer update to my proyect with Laravel 5, and I've seen that laravel has been updated to 5.0.6, giving me the error described in the title.

It's because Eloquent\Model::newFromBuilder() add an extra paremeter in this version.I have modified my own code in SleepingOwlModel::newFromBuilder() and by now everything is ok.

Sorry for my English

**Comment by sleeping-owl** [comment]
Thanks. Fixed.
