### ISSUE TITLE
Leaving a FormItem::select empty

### ISSUE THREAD

**Issue by esemtia-aaa** [sleeping-owl/admin#39]
Hi, I have a value in my database that can be nullable and you only can have one. How can I do a FormItem::select leaving value empty? Or I have to use a multiSelect and control that you only can have one?

**Comment by sleeping-owl** [comment]
This feature was added in the latest version. Update package (`composer update`) and publish assets:
* in Laravel 4.2:

    `php artisan asset:publish sleeping-owl/admin`
* in Laravel 5:

     `php artisan vendor:publish --provider="SleepingOwl\Admin\AdminServiceProvider" --tag="assets" --force`

Now you can mark select element to be nullable:
```php
FormItem::select('country_id', 'Country')->list('\Country')->nullable();
```
