### ISSUE TITLE
Custom Column

### ISSUE THREAD

**Issue by Nickbloor** [sleeping-owl/admin#40]
I am trying to create a custom column using the YesNoColumn.php using BaseColumn extend example.
But I am receiving the following error:
FatalErrorException in YesNoColumn.php line 10:
Cannot redeclare class YesNoColumn

I have used composer to autoload the YesNoColumn.php file (in admin/Custom/ folder)
This is been used in Admin::model
Column::yesNo('is_paid', 'Is_paid')->sortable(false);

and in the bootstrap folder I have added:
Column::register('yesNo', App\Admin\Custom\YesNoColumn::class);

However I have no Idea why I am receiving this error.

Kind Regards

Nick

**Comment by sleeping-owl** [comment]
This package automatically includes every `.php` file within `admin/` directory. You don't need to include it into your autoload.

I think removing composer autoload for this class will fix your issue.

**Comment by Nickbloor** [comment]
Thanks,
I have removed the autoload in composer and now it can't find the class.
I have stripped the code within bootstrap to Column::register('yesNo', YesNoColumn::class);
Now it says "Class YesNoColumn does not exist"

**Comment by sleeping-owl** [comment]
This package includes `admin/bootstrap.php` first and your class isn't yet defined at that moment. You can place your class outside of `admin/` directory and add autoload config to the composer to solve the issue.

If you think this is a problem and you want to place custom classes within `admin/` directory - I'll try to fix it.

**Comment by Nickbloor** [comment]
Thanks, I have found a workaround for now by putting the class inside the admin/bootstrap.php file.

**Comment by Nickbloor** [comment]
Thanks for all your help.
Finally I created a folder within the app folder and added the class file there.
I then used composer to reference it. This seems to work.
It isn't necessary to have the class file in the admin folder.

Thanks.
