### ISSUE TITLE
Замыкание в Controller->beforeFilter() вызывает Fatal error

### ISSUE THREAD

**Issue by TSka** [sleeping-owl/admin#41]
В /vendor/sleeping-owl/admin/src/SleepingOwl/Admin/Controllers/AdminController.php:67
в Controller->beforeFilter() передается замыкание, что в итоге вываливается в ошибку: 
>  php artisan route:list
> Fatal error: Call to a member function filter() on a non-object in /vendor/laravel/framework/src/Illuminate/Routing/Controller.php on line 111

```
			$this->beforeFilter(function (Route $route, Request $request)
			{
				if ($model = $route->parameter('model'))
				{
					$this->modelName = $model;
					$this->getModelItem();

					$this->modelRepository = App::make('SleepingOwl\Admin\Repositories\Interfaces\ModelRepositoryInterface', [
						'modelItem' => $this->modelItem,
						'request'   => $request
					]);

					$this->queryState->setPrefix($model);
				}
			});
```

**Comment by sleeping-owl** [comment]
Спасибо за найденную проблему. В версии 2.0.13 это исправлено.
