### ISSUE TITLE
The date paid is not a valid date.

### ISSUE THREAD

**Issue by Nickbloor** [sleeping-owl/admin#43]
Hi,
When I try and save using the timestamp, I get an 'The date paid is not a valid date.' Error
Eg, if I select 1st Jan 2015, I get 1/1/2015, 12:00:00 AM
but the error appears.
Funnily enough if I manually type in 2015-01-01 then this gets saved.

Regards

Nick

**Comment by sleeping-owl** [comment]
Please try it now with the latest version

**Comment by Nickbloor** [comment]
Thanks,
That seems to have resolved the issue.
I noticed date isn't saving either.
I didn't notice this before as I am not using them.

Regards

Nick

**Comment by sleeping-owl** [comment]
What locale are you using? I have `en` locale, field with `timestamp` type in my database and everything saves ok.

**Comment by Nickbloor** [comment]
Timestamp is now fixed. But when you try using time, it doesn't appear to save.

**Comment by sleeping-owl** [comment]
I've tried `FormItem::date` with both `date` and `timestamp` mysql field types - it works. What mysql field type are you using? Is there some attribute accessors in your model for this date field?

**Comment by Nickbloor** [comment]
The field type is datetime and there are no attribute accessors in the model.
There is no error when I save, but the field doesn't get updated.
I have tried changing the field type to date, but have the same issue.

It isn't important for me as I am using FormItem::timestamp and this works fine, especially if you cannot replicate the issue.

**Comment by sleeping-owl** [comment]
I've found the source of the issue. You must mark field as date in your model (http://laravel.com/docs/5.0/eloquent#date-mutators):

```php
public function getDates()
{
	return array_merge(parent::getDates(), ['date_paid']);
}
```

`Timestamp` form item converts date format by itself because laravel can't do it. But `Date` form item uses native laravel functions and your value "3/2/2015" won't be converted into "2015-03-02" without this method.

**Comment by Nickbloor** [comment]
Genius,
Thanks for your help.
