### ISSUE TITLE
instance id in Column/Control.php

### ISSUE THREAD

**Issue by JonasMe** [sleeping-owl/admin#44]
Hi SleepingOwn.

You should change the way id's are handled in the Column/Control.php ( Where the edit and destroy buttons are defined ) so that tabels/models with specific set $primaryKey attributes also are enabled.

At the moment you use : 
```$this->router->routeToDestroy($this->modelItem->getAlias(), $instance->id );```

Which does not work if the $primaryKey is set to something else than "id".

You should use

```$this->router->routeToDestroy($this->modelItem->getAlias(), $instance->getKey() ),```
( ```$instance->getKey()``` )

Which will fetch the current id of the model.

thanks in advance.

Jonas

**Comment by sleeping-owl** [comment]
Thanks. Fixed.
