### ISSUE TITLE
Form Item MultiSelect not saving

### ISSUE THREAD

**Issue by daverdalas** [sleeping-owl/admin#46]
I have a problem with saving the value of the MultiSelect. I have a multiselect declared in this way:

    FormItem::multiSelect('items', 'Przedmioty')->list(\App\Models\Item::class)->value('items.order_id');
In my model I've got this mutator function:

    public function items()
	{
		return $this->belongsToMany('App\Models\Item', 'order_items');
	}
    public function setItemsAttribute($items)
        {
            $this->items()->detach();
            if ( ! $items) return;
            if ( ! $this->exists) $this->save();

            $this->items()->attach($items);
        }

After selecting a few options and saveing I can see they are not saved and not added to the database. If I add in my mutator command die () I see that it is not even executed. I added to the database manually a few options and see that display correctly, but saveing does not work.
I am using Laravel 5. Any advices :)?

**Comment by Reals01** [comment]
also in the model, in variable "protected $fillable", should be add 'items'.

**Comment by daverdalas** [comment]
I had not thought about it. Thank you very much :)
