### ISSUE TITLE
Is there multiple select and bulk actions?

### ISSUE THREAD

**Issue by truetamtam** [sleeping-owl/admin#48]
Is there multiple select and bulk actions?

For example. Selecting with checkboxes few rows and pushing bulk buttons. Selected row's id's are away to some action.

**Comment by sleeping-owl** [comment]
There is no such features now.

**Comment by sleeping-owl** [comment]
Bulk actions were added in 3.0 version (under development now in `development` branch). You can see details in [displays docs](http://sleeping-owl.github.io/v3/en/Displays.html#table).
