### ISSUE TITLE
Adding a custom method

### ISSUE THREAD

**Issue by jadjoubran** [sleeping-owl/admin#49]
First off, thank you for this amazing package!

Imagine we have a `User` model and I want to add a custom method that says `Export as CSV` for example.
Where can I add the method, in which controller? In a way that it'll be only accessible for authenticated admins?

**Comment by sleeping-owl** [comment]
You can add new action to the `admin/menu.php`:
```php
Admin::menu()->url('my_url')->hidden()->uses('\App\HTTP\Controllers\Admin\MyController@action');
```
This will register `admin/my_url` route with admin middleware.

But you can't add buttons outside of table so I don't know where you can add link to this controller.

**Comment by jadjoubran** [comment]
Okay this partially saved my issue but the problem that I'm still having is the following:
/admin/my_url returns the output before all the HTML of the admin, so I'm getting the text before the Doctype of the admin. Is it possible to make it return the output inside the `#page-wrapper`?

**Comment by sleeping-owl** [comment]
Everything your controller action returns will be in `#page-wrapper`. It seems that there is something wrong with your controller action.

You can check it in my demo: http://sleepingowladmindemo.cloudcontrolled.com/admin/subdir/demo (credentials is admin / SleepingOwl).
Controller source: https://github.com/sleeping-owl/admin_demo/blob/master/app/controllers/AdminController.php
View source: https://github.com/sleeping-owl/admin_demo/blob/master/app/views/admin/second.blade.php

**Comment by jadjoubran** [comment]
oh okay that fixed my issue, thanks!

The demo was really helpful. I'm not sure if it's in the docs.. do you want me to add a reference for it in the docs?

**Comment by sleeping-owl** [comment]
There is link to the demo on http://sleeping-owl.github.io and in package readme. Where do you want to add the reference?

**Comment by jadjoubran** [comment]
okay my bad, just saw it.
Thanks again!
