### ISSUE TITLE
не отображается вся страница

### ISSUE THREAD

**Issue by wiyfn** [sleeping-owl/admin#57]
Сделал вот такой рабочий роут:
Route::get('/news/edit/{id}', 'Admin\NewsController@getEdit')->where('id', '[0-9]+');

public function getEdit()
{
    return view('admin.news.add');
}

Отображается только содержимое файла add.blade.php. Как сделать что бы отображалась остальная часть страници (шаблона). Я понимаю что нужно использовать в таких ситуациях конструкцию @extend. Только не могу понять что туда писать нужно.

Отображает только при условии если роут прописаный в меню. В моем случаии нет.
P.S. использую Laravel 5.0.14 :)

**Comment by sleeping-owl** [comment]
Используй метод `Admin::view($content, $title)`. В твоем случае код будет следующего вида:
```php
return Admin::view(view('admin.news.add')->render(), 'my page title');
```

**Comment by sleeping-owl** [comment]
Добавил новый функционал для работы с произвольными роутами, думаю будет удобней: http://sleeping-owl.github.io/ru/Routes/Custom_Routes.html
