### ISSUE TITLE
Create Custom Form Slug

### ISSUE THREAD

**Issue by atiladelcanton** [sleeping-owl/admin#60]
Hello
I need to create a form element to generate slug, put in is not very clear documentation about creating a form element.

Could you help me?

Tks!

**Comment by sleeping-owl** [comment]
Here is custom form item demo: https://gist.github.com/sleeping-owl/86e0a4be8de0715ac707
It simply adds 2 javascript files, 1 css file and 2 text fields. You can add your own javascript file and write all your logic there.
