### ISSUE TITLE
Own form element caching problem.

### ISSUE THREAD

**Issue by daverdalas** [sleeping-owl/admin#61]
Hey, 
First I would like of all to thank you for a great package.
I am creating my own form element with my own view for this element (formed in the method render of this element). 
I render blade file with foreach loop. Everything works at the beginning. But then when I send the form and get back with error states foreach loop value of $key is converted into a string '$key'.

Frist time

     @foreach($award_options as $key => $award_option)
     {{$key}}
     //output
     1, 2, 3
Second render

     //output
     $key, $key, $key
I suspect that it is your system cache or something. I would ask only for info how to turn it off for one project so I do not have to write the whole administrator panel from scratch :(

**Comment by sleeping-owl** [comment]
Can you provide the full code of your custom form item?
There is no caching for views. Your blade code works fine so I think there is the problem with `$award_options`, it seems to be broken after form send.

**Comment by daverdalas** [comment]
I discovered that the problem was caused by another add-on that I tried to use in the view. Thank you anyway for help :)
