### ISSUE TITLE
config/imagecache.php not found

### ISSUE THREAD

**Issue by RYZR** [sleeping-owl/admin#63]
With a fresh install of Laravel, I get this after running `php artisan admin:install`

```
  [Illuminate\Contracts\Filesystem\FileNotFoundException]
  File does not exist at path /home/ryzr/config/imagecache.php
```

I just installed the imagick.so extension for PHP5.4 as the installer recommended it to me earlier, but still no luck.

EDIT: I believe I fixed it by running

```
composer require intervention/imagecache
composer update
php artisan vendor:publish --provider="Intervention\Image\ImageServiceProviderLaravel5"
php artisan admin:install
```

**Comment by sleeping-owl** [comment]
Thanks. I fixed it in package.
