### ISSUE TITLE
Class 'App\Retailer' not found on test server but works on local machine

### ISSUE THREAD

**Issue by hrr** [sleeping-owl/admin#65]
I'm new to Laravel so i suspect the problem to be some missing config parameters. I can login to the admin panel and Retailer shows up in the side menu, but when I press it, it says "class not found". Works perfectly ok on my local machine which is an exact copy.

Is there any general thoughts about what could be wrong here?

Error: http://i.imgur.com/3SHQcRd.png

**Comment by hrr** [comment]
Fixed the problem by renaming the model files to start with capitalized character. (Why did it work on my local machine?)

**Comment by sleeping-owl** [comment]
Model filename must be exactly the same as model name. It can work in case-insensitive filesystems (windows or some mac os filesystems), but will not work in case-sensitive filesystems.
