### ISSUE TITLE
Unknown column 'overview_imageConfirmDelete' in 'field list' 

### ISSUE THREAD

**Issue by steve228uk** [sleeping-owl/admin#69]
I have an image field called `overview_image` that I'm trying to delete, upon doing so I get the following error:

    SQLSTATE[42S22]: Column not found: 1054 Unknown column 'overview_imageConfirmDelete' in 'field list' (SQL: update `pages` set `overview_image` = , `updated_at` = 2015-04-15 09:37:36, `overview_imageConfirmDelete` = on where `id` = 1)

I've tried adding that field in which does get rid of the error but it then won't delete the image at all. I can't seem to find this referenced in the documentation at all.

**Comment by steve228uk** [comment]
Anyone had this issue?

**Comment by sleeping-owl** [comment]
Update package to the latest version and add `protected $fillable = […]` to your model. This package uses eloquent mass assigment (http://laravel.com/docs/5.0/eloquent#mass-assignment)

**Comment by steve228uk** [comment]
I'm on the latest version (in fact there seems to be another issue with intervention/image's latest update and this package now) and have used `$guarded` instead of `$fillable` on the model.

This issue isn't a `MassAssignmentException` but rather it stating a column that doesn't seem to be documented anywhere doesn't exist.

**Comment by sleeping-owl** [comment]
I can't fix it in this version, you must use `$fillable` or add `<field-name>ConfirmDelete` for every image field to your `$guarded`. My package use mass assignment to fill the model with data from the form, but there is some additional fields that causes the bug.

Now I'm working on version 3.0 and this will be fixed there.

**Comment by mapeveri** [comment]
Hi, i have same problem, display this error: 

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'updated_at' in 'field list' (SQL: insert into `vad_paises` (`nm_pais`, `updated_at`, `created_at`) values (Italia, 2015-09-17 12:01:08, 2015-09-17 12:01:08))

The columns "updated_at" amd "created_at" not exists in my table of mysql.

My model is this::

class Pais extends SleepingOwlModel implements AuthenticatableContract,
                                    AuthorizableContract,
                                    CanResetPasswordContract
{
    use Authenticatable, Authorizable, CanResetPassword;

    protected $guarded = ['id_Pais', "nm_pais"];
    protected $fillable = ['id_Pais', 'nm_pais'];
    protected $table = 'vad_paises';
}

How can i fix this?.

Thanks!

**Comment by mapeveri** [comment]
I solved with this line in the model:
  
   public $timestamps = false;

**Comment by steve228uk** [comment]
@mapeveri I'd probably recommend you add the timestamps to your migration rather than suppressing them. They can prove to be very handy.
