### ISSUE TITLE
->with(model list) not working.

### ISSUE THREAD

**Issue by vnandan** [sleeping-owl/admin#71]
I tried adding eager loading of models but it didn't work.
`User.php`
```
Admin::model(App\User::class)
		->title('Users')
        ->as('users')
      	->columns(function ()
		{
	    	Column::string('email', 'Email');
		})
        ->form(function ()
		{
    		FormItem::text('email', 'Email');
		}
		);
```
`Url.php`
```
<?php
Admin::model(App\Url::class)
        ->as('urls')
        ->title('Urls')
        ->with('users')
      	->columns(function()
		{
	    	Column::string('url', 'URL');
		})
        ->form(function ()
		{
    		FormItem::text('url', 'URL');
		}
		);
```

`BadMethodCallException in Builder.php line 1992:
Call to undefined method Illuminate\Database\Query\Builder::users()`

**Comment by vnandan** [comment]
Problem with relations between User and Url.

**Comment by jingyibo123** [comment]
hi @vnandan 
did you solve it by adding a function in the URL model similar to: 
`public function users()`
	`{`
		`return $this->belongsToMany('users');`
	`}`
Thank you in advance
