### ISSUE TITLE
Merge menu with the 'front-end'

### ISSUE THREAD

**Issue by joancifo** [sleeping-owl/admin#74]
I really love Sleeping Owl. I'm using Laravel 5.

I was wondering if there are any option to merge the sb-admin-2 lateral menu with an other one.
Explanation:

I would like making a lateral menu called Administrator of an other sb-admin-2 (the main app.) which would be a dropdown menu that includes "the sleeping owl lateral menu" with all its features.
Well, the top menu of sleeping owl would be removed and the auth would be done by Laravel.

Of course and option would be remove the app menu and use the sleeping owl system, but I don't like using the prefix /admin for pages that aren't for administration.

Thank you.

**Comment by sleeping-owl** [comment]
You can get all menu items with this code:
```php
$items = Admin::instance()->menu->getItems();
```
and render them:
```
@foreach ($items as $item)
  {!! $item->render() !!}
@endforeach
```

But there will be a problem with admin routes, you cannot get a center part of the admin page and insert it into your layout. If you want to solve it you must publish views from package and update it layout by yourself.

**Comment by kanashin** [comment]
Thank you for your fast answer!

It's fine for me. Using getItems will be enough.

I'm not sure if I should open a new topic but here we go: 
I'm having a problem with re-authenticate. I set the auth using Eloquent, but /admin is asking for re-auth. Is single-auth possible?

Thank you!

**Comment by acacha** [comment]
UPDATE:

I think in new versions (v3 maybe?) you have to use:

            $items = Admin::instance()->getMenu();

instead of:

 $items = Admin::instance()->menu->getItems();
