### ISSUE TITLE
Default sort issue

### ISSUE THREAD

**Issue by xcopy** [sleeping-owl/admin#75]
Here is the my model. Overriding `scopeDefaultSort($query)`.

```php
class Category extends SleepingOwlModel {

	public function scopeDefaultSort($query)
	{
		return $query->orderBy($this->primaryKey, 'desc');
	}

}
```

But categories actually ordered by primary key ASC (look at screenshot) by default.

![screenshot from 2015-04-27 10 37 20](https://cloud.githubusercontent.com/assets/202339/7341766/beab081e-ecc9-11e4-8518-145341906700.png)

SQL:

```sql
select * from `administrators` where `administrators`.`id` = '1' limit 1
select count(*) as aggregate from `categories` order by `id` desc
select `categories`.* from `categories` order by `id` desc
```

Little confused. Sorry if I missed something in docs.

**Comment by sleeping-owl** [comment]
Default sort is applied to the sql queries, but datatables plugin sorts table by itself.
To solve your issue:
 - run `composer update` (`sleeping-owl/admin` package will be updated to version 2.0.31)
 - run `php artisan vendor:publish --provider=SleepingOwl/Admin/AdminServiceProvider --tag=assets --force`
 - in your columns definition set default sortable:

    ```php
    Column::string('id', 'ID')->sortableDefault('desc')
     ```

This will override datatables default sort feature.

**Comment by xcopy** [comment]
Yes, I can see version 2.0.31, but nothing changes :(

**Comment by sleeping-owl** [comment]
Has you added `->sortableDefault('desc')` to your column?

**Comment by xcopy** [comment]
Sure

```php
Admin::model(App\Models\Blog\Category::class)
	->title('Categories')
	->columns(function()
	{
		Column::string('id')->sortableDefault('desc');
		Column::string('title');
	});
```

**Comment by xcopy** [comment]
![screenshot from 2015-04-27 21 39 09](https://cloud.githubusercontent.com/assets/202339/7351433/f5109cfe-ed26-11e4-96c2-eadaf1617ee9.png)
---
![screenshot from 2015-04-27 21 41 45](https://cloud.githubusercontent.com/assets/202339/7351436/f92fbb4e-ed26-11e4-86db-5991d9ab825a.png)

**Comment by sleeping-owl** [comment]
It seems like you haven't published assets from the 2.0.31 package version or it caused by your browser cache.

**Comment by xcopy** [comment]
`composer.lock`

```json
{
	"name": "sleeping-owl/admin",
	"version": "2.0.31",
	"source": {
	    "type": "git",
	    "url": "https://github.com/sleeping-owl/admin.git",
	    "reference": "6a04041bd3a71ceab32b717a5436e0ffae277bf0"
	}
}
```

PHP:
```php
Admin::model(App\Models\Blog\Category::class)
	->title('Categories')
	->columns(function()
	{
		Column::string('id')->sortableDefault('desc');
		Column::string('title');
	})
```

HTML:

```html
<th data-sortable-default="desc" style="width: 120px;" class="sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Id: activate to sort column ascending">Id</th>
```

`admin.js` line 44:
![screenshot from 2015-04-29 09 52 28](https://cloud.githubusercontent.com/assets/202339/7384492/f3ff8926-ee55-11e4-93cd-692f0fc9200c.png)

**Comment by sleeping-owl** [comment]
Manually copy file from `vendor/sleeping-owl/admin/public/all.min.js` to `public/packages/sleeping-owl/admin/all.min.js`and try again.

**Comment by xcopy** [comment]
Same :(

**Comment by sleeping-owl** [comment]
This may be caused by datatables state save feature. It saves your sort order and restores it in the following requests, while my package sets only default order.

**Comment by xcopy** [comment]
So, what is the solution?

**Comment by sleeping-owl** [comment]
Try another browser or private mode. Correct sort order means that it's not a bug, but datatables feature. If you want to disable datatables ordering feature you can add `->sortable(false)` for each column.

**Comment by xcopy** [comment]
When I click some menu item ("Categories" for example) - I can see the table sorted correctly (ie. sorted by ID desc), but after blink (or like DOM ready) I see old behavior (ie. sorted by ID asc) again.

**Comment by xcopy** [comment]
> Try another browser or private mode.

Same

**Comment by xcopy** [comment]
Okay. Let me show you something.

Please, look at this fiddle http://jsfiddle.net/xcopy/Len9zt72/

```html
<th ... aria-sort="descending" ...>Age</th>
```
```js
$('#example').dataTable( {
    "order": [[ 3, "desc" ]]
} );
```

and 

```html
<th ... aria-sort="ascending" ...>Age</th>
```
```js
$('#example').dataTable( {
    "order": [[ 3, "asc" ]]
} );
```

This is correct behavior.

---

Now, my data table (incorrect behavior).

```php
Column::string('id')->sortableDefault('desc');
```
```html
<th data-sortable-default="desc" ... aria-sort="ascending" ...>Id</th>
```

and 

```php
Column::string('id')->sortableDefault('asc');
```
```html
<th data-sortable-default="asc" ... aria-sort="ascending" ...>Id</th>
```

ie. `aria-sort="ascending"` anyway.

---

What you think?

**Comment by sleeping-owl** [comment]
Sorry, but I can't reproduce your bug.

Here is my column definition:
```php
Column::string('id', 'ID')->sortableDefault('desc');
```

Here is the source code I've got after first visit (table sorted by id descending):

![2015-04-30 15 24 06](https://cloud.githubusercontent.com/assets/9197310/7411841/9e395c16-ef44-11e4-96fc-8ba21e7c99e2.png)

After that I've clicked on column header and refreshed the page and got table sorted by id ascending:

![2015-04-30 15 25 39](https://cloud.githubusercontent.com/assets/9197310/7411856/d0a1e0ec-ef44-11e4-96e4-8caaebc559f5.png)

But default sort was correct.

----

As an experiment try to disable datatables state save feature: edit `public/packages/sleeping-owl/admin/all.min.js` file, find `stateSave:!0` and replace with `stateSave:false`. If this solution will work I'll add this as a parameter.

**Comment by xcopy** [comment]
Just changed `stateSave: false` manually.. and it works properly as expected! 

Waiting for next release :+1:

**Comment by xcopy** [comment]
@sleeping-owl, still waiting for next release

**Comment by sleeping-owl** [comment]
Update package to the version 2.0.32 and publish assets (`php artisan vendor:publish --tag=assets --force`).

Now you can disable state save feature (it's enabled by default):
```php
Admin::model('\App\Company')->stateSave(false)->...
```
