### ISSUE TITLE
Model definition

### ISSUE THREAD

**Issue by noxify** [sleeping-owl/admin#77]
Hi,

currently I'm playing a bit around with your package.

At first  - Thanks a lot! It's awesome what I can do with it.

Now my problem.

I'm using the modules package from pingpong labs.
Now I'm trying to add a new menu entry from my module.

The menu will be shown - That's okay.
But if I click on a link I got the following error message:
```
Routing requirement for "adminModel" cannot be empty.
```

My model configuration looks like this:
```
\Admin::model('Modules\Sentry\Entities\User')->title('My Model Title')->display(function ()
{
	$display = AdminDisplay::datatables();
	$display->with();
	$display->filters([

	]);
	$display->columns([
		Column::string('title')->label('Title'),
		Column::string('image')->label('Image'),
		Column::string('date')->label('Date'),
		Column::string('entries')->label('Entries'),
	]);
	return $display;
})->createAndEdit(function ()
{
	$form = AdminForm::form();
	$form->items([
		FormItem::text('email', 'Email'),
		FormItem::text('password', 'Password'),
		FormItem::checkbox('activated', 'Activated'),
		FormItem::text('activation_code', 'Activation Code'),
		FormItem::timestamp('activated_at', 'Activated At')->format('d.m.Y'),//->seconds(true),
		FormItem::timestamp('last_login', 'Last Login')->format('d.m.Y'),//->seconds(true),
		FormItem::text('persist_code', 'Persist Code'),
		FormItem::text('reset_password_code', 'Reset Password Code'),
		FormItem::text('first_name', 'First Name'),
		FormItem::text('last_name', 'Last Name'),
		FormItem::ckeditor('permissions', 'Permissions'),
	]);
	return $form;
});
```

If I copy this code directly in the `app/Admin/User.php` it will works fine.

My composer.json is the following:

```
"laravel/framework": "5.0.*",
		"pseudoagentur/sleeping-owl-admin-sentry-admin-lte": "dev-development",
		"cartalyst/sentry": "dev-feature/laravel-5",
		"barryvdh/laravel-debugbar": "^2.0",
		"pingpong/generators": "2.0.*@dev",
		"pingpong/modules": "2.0.*@dev",
		"guidovanbiemen/laravel-whoops": "^1.0"
```

P.S. I have created my own repo, because I want to use sentry as authentication :)

Any idea? Thanks a lot :)

**Comment by sleeping-owl** [comment]
All your model configurations must be loaded by BootstrapServiceProvider (https://github.com/sleeping-owl/admin/blob/development/src/SleepingOwl/Admin/Providers/BootstrapServiceProvider.php). It requires every file within `app/admin` directory.

If you don't want to use this directory you must initialize your module (and model configuration) before `SleepingOwl\Admin\AdminServiceProvider` call. At the time it runs it must know all models it can manage.

**Comment by noxify** [comment]
My first idea was to update the BootstrapServiceProvider but I think it's better to create a small package which handles this. The package will be called before the AdminServiceProvider and it will do then the same as the BootstrapServiceProvider:

```
public function register()
	{
		$this->directory = config('admin.bootstrapDirectory');
		if ( ! is_dir($this->directory))
		{
			return;
		}
		$files = $this->getAllFiles();
		foreach ($files as $file)
		{
			require $file;
		}
	}

	protected function getAllFiles()
	{
		$files = Finder::create()->files()->name('/^.+\.php$/')->notName('routes.php')->in($this->directory);
		$files->sort(function ($a)
		{
			return $a->getFilename() !== static::BOOTSRAP_FILE;
		});
		return $files;
	}
```

Thanks!
