### ISSUE TITLE
how to declare password fields in model?

### ISSUE THREAD

**Issue by eugenem** [sleeping-owl/admin#80]
Say I want administrators or users table to be editable by CRUD.

Btw, when I try to edit admin through the editor, it crashes complaining missing 'validate' method.

**Comment by sleeping-owl** [comment]
Please paste full exception description and your form configuration here.

**Comment by eugenem** [comment]
Actually I did this and it seems to work. 
```
FormItem::register('password', function ($instance)
{
    return "<div class='form-group'>
<label>Set password</label>
<input class='form-control' type='password' id='password' name='password' />
</div>";
});
```
I'd expect though that label and field id would pass as params to this function, as with all other form fields...

**Comment by eugenem** [comment]
To make admins table editable I did the same trick to your Administrator class:
```
class Administrator extends \SleepingOwl\Models\SleepingOwlModel implements AuthenticatableContract
{
	use Authenticatable;

	protected $fillable = [
		'username',
		'password',
		'name',
	];

	protected $hidden = [
		'password',
		'remember_token',
	];

    public function setPasswordAttribute($value)
    {
        if( $value )
            $this->attributes['password'] = bcrypt($value);
    }
}
```

I think this might require AdministratorsCommand update to not use password hashing.

Would you accept this change?

**Comment by sleeping-owl** [comment]
You can make a pull request for this.

**Comment by eugenem** [comment]
I'm not sure this is a good idea. I can't check command functionality, because locally I don't have DB, and at server I don't have SSH. And changing only model without command might break the command...

**Comment by sleeping-owl** [comment]
I've added it by myself.

**Comment by eugenem** [comment]
you forgot this to make admins editable:

    class Administrator extends \SleepingOwl\Models\SleepingOwlModel

**Comment by sleeping-owl** [comment]
Fixed it
