### ISSUE TITLE
Model filter based on logged in administrator

### ISSUE THREAD

**Issue by Elyahou** [sleeping-owl/admin#81]
I want to have many administrators, and each will have access to selected rows of each models, for example admin with `app_id=1` will have access to product, categories, images that have `app_id=1`

Is there a way to do this with the admin package ?

**Comment by sleeping-owl** [comment]
You can add the following code to your model configuration:
```php
Admin::model('MyModel')->denyEditingAndDeleting(function ($instance)
{
	return AdminAuth::user()->id != $instance->id;
})
```

**Comment by Elyahou** [comment]
Thank you for your help !

Is there a way to do not display at all these rows and not only deny editing ?

**Comment by sleeping-owl** [comment]
You can take a look at the upcoming 3.0 version  - http://sleeping-owl.github.io/v3/en/Introduction.html.

Package was rewritten from scratch and doesn't have backward compatibility. But has some new features and can help you with your problem. You can use table display type and apply scope (http://sleeping-owl.github.io/v3/en/Displays.html#table):

```php
// in model configuration
$display->scope('admin');

// in model
public function scopeAdmin($query)
{
  $query->where('id', \AdminAuth::user()->id);
}
```

In the current package version you can't hide rows.

**Comment by Elyahou** [comment]
This seem very interesting.

Have you an idea when it will go to stable ?

**Comment by sleeping-owl** [comment]
It will be released in a week or two.

**Comment by kanashin** [comment]
I don't know if I should open a new issue because I having exactly the same question.

v3:

Using scope works fine when hiding rows, but how could I forbid the edition of item?

For example, if I go manually to this url and the user doesn't own XX post it can still edit it.
How could I deny the connection? 
http://localhost/admin/posts/XX/edit

**Comment by jingyibo123** [comment]
@sleeping-owl 
Hi, I have a little question about this.
You mentioned above that "In the current package version you can't hide rows."
I'm trying to build with your plugin a system where different users can add items in the same model(album, eg), but one user only has access(view, edit or delete) to his own items.
Can we specify that condition by modifying the query line in the current version?
Thanks a lot!
