### ISSUE TITLE
Exception using validationRule($) on FormItem

### ISSUE THREAD

**Issue by iamfreee** [sleeping-owl/admin#82]
Hi,

I am loving this package!

When i am trying to use:

`FormItem::text('first_name', 'First Name')->validationRule('required|min:2');``

Throws an exception:

`ErrorException in MessageBag.php line 183:
Array to string conversion`

Can you check it? Thanks!

**Comment by sleeping-owl** [comment]
Try 2.0.34 version, it must fix the bug.

**Comment by iamfreee** [comment]
Fixed!

Thanks!
