### ISSUE TITLE
Strange last column in datatables

### ISSUE THREAD

**Issue by iamfreee** [sleeping-owl/admin#84]
Hi,

![2015-05-11_16-04-05](https://cloud.githubusercontent.com/assets/1500881/7567971/1251fa0c-f7f8-11e4-914b-cabe433a0764.png)

![2015-05-11_16-04-22](https://cloud.githubusercontent.com/assets/1500881/7567974/18bfe642-f7f8-11e4-9c26-ecc27349f3ea.png)

It's a bit annoying.

**Comment by sleeping-owl** [comment]
It is the column header for the column with action buttons. What's wrong?

**Comment by iamfreee** [comment]
Yep, my bad!

Sorry
