### ISSUE TITLE
How to hide/remove 'delete' buttons?

### ISSUE THREAD

**Issue by eugenem** [sleeping-owl/admin#86]
Can I add custom css?
Or maybe edit grid template somehow?

**Comment by sleeping-owl** [comment]
You can only disable them, but not hide.

You can try new version (http://sleeping-owl.github.io/v3/en/Getting_Started/Installation.html) - you can disable delete feature for some entries or at all. But this version is incompatible with previous.

**Comment by eugenem** [comment]
cool! will try new version soon. it also got async datatables that i need
