### ISSUE TITLE
Как создать форму для связаных моделей?

### ISSUE THREAD

**Issue by Necronru** [sleeping-owl/admin#87]
Например у меня есть две модели:

	class Member extends Model {

		public function passport() {
			return $this->hasOne('Passport');
		}
	}

	class Passport extends Model {	

		public function member() {
			return $this->belongsTo('Member');
		}

	}

Как внутри формы для Member создать форму для создания/редактирования связаной модели Passport?

**Comment by sleeping-owl** [comment]
Используя текущую версию - никак. В новой версии (которая сейчас в бета-тестировании) это можно реализовать: [пример](http://sleepingowladmindemo2.cloudcontrolled.com/admin/contacts3/4/edit) (логин/пароль: admin/SleepingOwl), [исходный код примера](https://github.com/sleeping-owl/admin-3-demo/blob/master/app/admin/Contact3.php).

Документацию по новой версии можно посмотреть [тут](http://sleeping-owl.github.io/v3/ru/Getting_Started/Installation.html).

**Comment by Necronru** [comment]
Спасибо!
