### ISSUE TITLE
Ckeditor Upload Images Not Working

### ISSUE THREAD

**Issue by iamfreee** [sleeping-owl/admin#88]
Hi,

While trying to upload an image i get an exception: Illuminate\Session\TokenMismatchException.

Thanks!

**Comment by sleeping-owl** [comment]
I can't fix this bug in the current version, you have to manually disable csrf protection for this route: `images/upload` (http://www.camroncade.com/disable-csrf-for-specific-routes-laravel-5/).

This bug is already fixed in the upcoming 3.0 version.

**Comment by iamfreee** [comment]
Thanks!
